// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/approval_workflow.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	io "io"
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockApprovalWorkflowService is a mock of ApprovalWorkflowService interface.
type MockApprovalWorkflowService struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalWorkflowServiceMockRecorder
}

// MockApprovalWorkflowServiceMockRecorder is the mock recorder for MockApprovalWorkflowService.
type MockApprovalWorkflowServiceMockRecorder struct {
	mock *MockApprovalWorkflowService
}

// NewMockApprovalWorkflowService creates a new mock instance.
func NewMockApprovalWorkflowService(ctrl *gomock.Controller) *MockApprovalWorkflowService {
	mock := &MockApprovalWorkflowService{ctrl: ctrl}
	mock.recorder = &MockApprovalWorkflowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalWorkflowService) EXPECT() *MockApprovalWorkflowServiceMockRecorder {
	return m.recorder
}

// CreateApprovalFlow mocks base method.
func (m *MockApprovalWorkflowService) CreateApprovalFlow(c *gin.Context, tableCode string, approvalInfo map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApprovalFlow", c, tableCode, approvalInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApprovalFlow indicates an expected call of CreateApprovalFlow.
func (mr *MockApprovalWorkflowServiceMockRecorder) CreateApprovalFlow(c, tableCode, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApprovalFlow", reflect.TypeOf((*MockApprovalWorkflowService)(nil).CreateApprovalFlow), c, tableCode, approvalInfo)
}

// CreateApprovalInstance mocks base method.
func (m *MockApprovalWorkflowService) CreateApprovalInstance(c *gin.Context, approvalDefinition *model.ApprovalDefinition, approvalNodes []*model.ApprovalNode, approvalInfo map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApprovalInstance", c, approvalDefinition, approvalNodes, approvalInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApprovalInstance indicates an expected call of CreateApprovalInstance.
func (mr *MockApprovalWorkflowServiceMockRecorder) CreateApprovalInstance(c, approvalDefinition, approvalNodes, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApprovalInstance", reflect.TypeOf((*MockApprovalWorkflowService)(nil).CreateApprovalInstance), c, approvalDefinition, approvalNodes, approvalInfo)
}

// CreateApprovalTask mocks base method.
func (m *MockApprovalWorkflowService) CreateApprovalTask(c *gin.Context, node *model.ApprovalNode, approvalInfo map[string]string) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApprovalTask", c, node, approvalInfo)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApprovalTask indicates an expected call of CreateApprovalTask.
func (mr *MockApprovalWorkflowServiceMockRecorder) CreateApprovalTask(c, node, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApprovalTask", reflect.TypeOf((*MockApprovalWorkflowService)(nil).CreateApprovalTask), c, node, approvalInfo)
}

// CreateDraftWithApproval mocks base method.
func (m *MockApprovalWorkflowService) CreateDraftWithApproval(c *gin.Context, tableCode, reason string, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraftWithApproval", c, tableCode, reason, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDraftWithApproval indicates an expected call of CreateDraftWithApproval.
func (mr *MockApprovalWorkflowServiceMockRecorder) CreateDraftWithApproval(c, tableCode, reason, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraftWithApproval", reflect.TypeOf((*MockApprovalWorkflowService)(nil).CreateDraftWithApproval), c, tableCode, reason, entityMap)
}

// CreateStartTask mocks base method.
func (m *MockApprovalWorkflowService) CreateStartTask(c *gin.Context, startNode *model.ApprovalNode, approvalInfo map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStartTask", c, startNode, approvalInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStartTask indicates an expected call of CreateStartTask.
func (mr *MockApprovalWorkflowServiceMockRecorder) CreateStartTask(c, startNode, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStartTask", reflect.TypeOf((*MockApprovalWorkflowService)(nil).CreateStartTask), c, startNode, approvalInfo)
}

// EvaluateConditionNode mocks base method.
func (m *MockApprovalWorkflowService) EvaluateConditionNode(approvalNodes []*model.ApprovalNode, conditionNode *model.ApprovalNode, formData map[string]any) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateConditionNode", approvalNodes, conditionNode, formData)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateConditionNode indicates an expected call of EvaluateConditionNode.
func (mr *MockApprovalWorkflowServiceMockRecorder) EvaluateConditionNode(approvalNodes, conditionNode, formData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateConditionNode", reflect.TypeOf((*MockApprovalWorkflowService)(nil).EvaluateConditionNode), approvalNodes, conditionNode, formData)
}

// FindNodeByCode mocks base method.
func (m *MockApprovalWorkflowService) FindNodeByCode(approvalNodes []*model.ApprovalNode, nodeCode string) *model.ApprovalNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNodeByCode", approvalNodes, nodeCode)
	ret0, _ := ret[0].(*model.ApprovalNode)
	return ret0
}

// FindNodeByCode indicates an expected call of FindNodeByCode.
func (mr *MockApprovalWorkflowServiceMockRecorder) FindNodeByCode(approvalNodes, nodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNodeByCode", reflect.TypeOf((*MockApprovalWorkflowService)(nil).FindNodeByCode), approvalNodes, nodeCode)
}

// GenerateSerialNumber mocks base method.
func (m *MockApprovalWorkflowService) GenerateSerialNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSerialNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSerialNumber indicates an expected call of GenerateSerialNumber.
func (mr *MockApprovalWorkflowServiceMockRecorder) GenerateSerialNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSerialNumber", reflect.TypeOf((*MockApprovalWorkflowService)(nil).GenerateSerialNumber))
}

// GetNextApprovalNode mocks base method.
func (m *MockApprovalWorkflowService) GetNextApprovalNode(approvalNodes []*model.ApprovalNode, currentNode *model.ApprovalNode, formData map[string]any) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextApprovalNode", approvalNodes, currentNode, formData)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextApprovalNode indicates an expected call of GetNextApprovalNode.
func (mr *MockApprovalWorkflowServiceMockRecorder) GetNextApprovalNode(approvalNodes, currentNode, formData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextApprovalNode", reflect.TypeOf((*MockApprovalWorkflowService)(nil).GetNextApprovalNode), approvalNodes, currentNode, formData)
}

// GetOperationInfo mocks base method.
func (m *MockApprovalWorkflowService) GetOperationInfo(operation string, operationInfo *map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationInfo", operation, operationInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetOperationInfo indicates an expected call of GetOperationInfo.
func (mr *MockApprovalWorkflowServiceMockRecorder) GetOperationInfo(operation, operationInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationInfo", reflect.TypeOf((*MockApprovalWorkflowService)(nil).GetOperationInfo), operation, operationInfo)
}

// ImportWithApproval mocks base method.
func (m *MockApprovalWorkflowService) ImportWithApproval(c *gin.Context, tableCode, reason, operation string, r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportWithApproval", c, tableCode, reason, operation, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportWithApproval indicates an expected call of ImportWithApproval.
func (mr *MockApprovalWorkflowServiceMockRecorder) ImportWithApproval(c, tableCode, reason, operation, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportWithApproval", reflect.TypeOf((*MockApprovalWorkflowService)(nil).ImportWithApproval), c, tableCode, reason, operation, r)
}

// ParseApproverConfig mocks base method.
func (m *MockApprovalWorkflowService) ParseApproverConfig(node *model.ApprovalNode, assigneeID, assigneeName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseApproverConfig", node, assigneeID, assigneeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseApproverConfig indicates an expected call of ParseApproverConfig.
func (mr *MockApprovalWorkflowServiceMockRecorder) ParseApproverConfig(node, assigneeID, assigneeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseApproverConfig", reflect.TypeOf((*MockApprovalWorkflowService)(nil).ParseApproverConfig), node, assigneeID, assigneeName)
}

// UpdateByIdsWithApproval mocks base method.
func (m *MockApprovalWorkflowService) UpdateByIdsWithApproval(c *gin.Context, tableCode, reason string, ids []uint, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIdsWithApproval", c, tableCode, reason, ids, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByIdsWithApproval indicates an expected call of UpdateByIdsWithApproval.
func (mr *MockApprovalWorkflowServiceMockRecorder) UpdateByIdsWithApproval(c, tableCode, reason, ids, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIdsWithApproval", reflect.TypeOf((*MockApprovalWorkflowService)(nil).UpdateByIdsWithApproval), c, tableCode, reason, ids, entityMap)
}

// UpdateDraftWithApproval mocks base method.
func (m *MockApprovalWorkflowService) UpdateDraftWithApproval(c *gin.Context, tableCode, reason string, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraftWithApproval", c, tableCode, reason, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDraftWithApproval indicates an expected call of UpdateDraftWithApproval.
func (mr *MockApprovalWorkflowServiceMockRecorder) UpdateDraftWithApproval(c, tableCode, reason, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraftWithApproval", reflect.TypeOf((*MockApprovalWorkflowService)(nil).UpdateDraftWithApproval), c, tableCode, reason, entityMap)
}
