// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/approval_definition.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockApprovalDefinitionService is a mock of ApprovalDefinitionService interface.
type MockApprovalDefinitionService struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalDefinitionServiceMockRecorder
}

// MockApprovalDefinitionServiceMockRecorder is the mock recorder for MockApprovalDefinitionService.
type MockApprovalDefinitionServiceMockRecorder struct {
	mock *MockApprovalDefinitionService
}

// NewMockApprovalDefinitionService creates a new mock instance.
func NewMockApprovalDefinitionService(ctrl *gomock.Controller) *MockApprovalDefinitionService {
	mock := &MockApprovalDefinitionService{ctrl: ctrl}
	mock.recorder = &MockApprovalDefinitionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalDefinitionService) EXPECT() *MockApprovalDefinitionServiceMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockApprovalDefinitionService) Activate(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockApprovalDefinitionServiceMockRecorder) Activate(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Activate), id)
}

// BatchDelete mocks base method.
func (m *MockApprovalDefinitionService) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalDefinitionServiceMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalDefinitionService)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockApprovalDefinitionService) BatchUpdate(c *gin.Context, ids []uint, approvalDefinition *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, approvalDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalDefinitionServiceMockRecorder) BatchUpdate(c, ids, approvalDefinition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalDefinitionService)(nil).BatchUpdate), c, ids, approvalDefinition)
}

// CanDelete mocks base method.
func (m *MockApprovalDefinitionService) CanDelete(id uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDelete", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanDelete indicates an expected call of CanDelete.
func (mr *MockApprovalDefinitionServiceMockRecorder) CanDelete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDelete", reflect.TypeOf((*MockApprovalDefinitionService)(nil).CanDelete), id)
}

// CanEdit mocks base method.
func (m *MockApprovalDefinitionService) CanEdit(id uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanEdit", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanEdit indicates an expected call of CanEdit.
func (mr *MockApprovalDefinitionServiceMockRecorder) CanEdit(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanEdit", reflect.TypeOf((*MockApprovalDefinitionService)(nil).CanEdit), id)
}

// Create mocks base method.
func (m *MockApprovalDefinitionService) Create(c *gin.Context, approvalDefinition *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, approvalDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalDefinitionServiceMockRecorder) Create(c, approvalDefinition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Create), c, approvalDefinition)
}

// CreateNewVersion mocks base method.
func (m *MockApprovalDefinitionService) CreateNewVersion(c *gin.Context, id uint, comment string) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewVersion", c, id, comment)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewVersion indicates an expected call of CreateNewVersion.
func (mr *MockApprovalDefinitionServiceMockRecorder) CreateNewVersion(c, id, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewVersion", reflect.TypeOf((*MockApprovalDefinitionService)(nil).CreateNewVersion), c, id, comment)
}

// Deactivate mocks base method.
func (m *MockApprovalDefinitionService) Deactivate(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockApprovalDefinitionServiceMockRecorder) Deactivate(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Deactivate), id)
}

// Delete mocks base method.
func (m *MockApprovalDefinitionService) Delete(c *gin.Context, id uint) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalDefinitionServiceMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Delete), c, id)
}

// First mocks base method.
func (m *MockApprovalDefinitionService) First(where map[string]any) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalDefinitionServiceMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalDefinitionService)(nil).First), where)
}

// Get mocks base method.
func (m *MockApprovalDefinitionService) Get(id uint) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApprovalDefinitionServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Get), id)
}

// GetActiveByEntityCode mocks base method.
func (m *MockApprovalDefinitionService) GetActiveByEntityCode(entityCode string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByEntityCode", entityCode)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByEntityCode indicates an expected call of GetActiveByEntityCode.
func (mr *MockApprovalDefinitionServiceMockRecorder) GetActiveByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByEntityCode", reflect.TypeOf((*MockApprovalDefinitionService)(nil).GetActiveByEntityCode), entityCode)
}

// GetByCategory mocks base method.
func (m *MockApprovalDefinitionService) GetByCategory(category string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategory", category)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategory indicates an expected call of GetByCategory.
func (mr *MockApprovalDefinitionServiceMockRecorder) GetByCategory(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockApprovalDefinitionService)(nil).GetByCategory), category)
}

// GetByCode mocks base method.
func (m *MockApprovalDefinitionService) GetByCode(code string) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", code)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockApprovalDefinitionServiceMockRecorder) GetByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockApprovalDefinitionService)(nil).GetByCode), code)
}

// GetByEntityCode mocks base method.
func (m *MockApprovalDefinitionService) GetByEntityCode(entityCode string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEntityCode", entityCode)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEntityCode indicates an expected call of GetByEntityCode.
func (mr *MockApprovalDefinitionServiceMockRecorder) GetByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEntityCode", reflect.TypeOf((*MockApprovalDefinitionService)(nil).GetByEntityCode), entityCode)
}

// GetLatestVersion mocks base method.
func (m *MockApprovalDefinitionService) GetLatestVersion(code string) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", code)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockApprovalDefinitionServiceMockRecorder) GetLatestVersion(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockApprovalDefinitionService)(nil).GetLatestVersion), code)
}

// GetVersions mocks base method.
func (m *MockApprovalDefinitionService) GetVersions(code string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersions", code)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersions indicates an expected call of GetVersions.
func (mr *MockApprovalDefinitionServiceMockRecorder) GetVersions(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersions", reflect.TypeOf((*MockApprovalDefinitionService)(nil).GetVersions), code)
}

// List mocks base method.
func (m *MockApprovalDefinitionService) List(page, pageSize int, total *int64, where map[string]any) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApprovalDefinitionServiceMockRecorder) List(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApprovalDefinitionService)(nil).List), page, pageSize, total, where)
}

// Publish mocks base method.
func (m *MockApprovalDefinitionService) Publish(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockApprovalDefinitionServiceMockRecorder) Publish(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Publish), id)
}

// Update mocks base method.
func (m *MockApprovalDefinitionService) Update(c *gin.Context, approvalDefinition *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, approvalDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalDefinitionServiceMockRecorder) Update(c, approvalDefinition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalDefinitionService)(nil).Update), c, approvalDefinition)
}

// ValidateDefinition mocks base method.
func (m *MockApprovalDefinitionService) ValidateDefinition(def *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDefinition", def)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateDefinition indicates an expected call of ValidateDefinition.
func (mr *MockApprovalDefinitionServiceMockRecorder) ValidateDefinition(def interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDefinition", reflect.TypeOf((*MockApprovalDefinitionService)(nil).ValidateDefinition), def)
}
