// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/approval.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	io "io"
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockApprovalService is a mock of ApprovalService interface.
type MockApprovalService struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalServiceMockRecorder
}

// MockApprovalServiceMockRecorder is the mock recorder for MockApprovalService.
type MockApprovalServiceMockRecorder struct {
	mock *MockApprovalService
}

// NewMockApprovalService creates a new mock instance.
func NewMockApprovalService(ctrl *gomock.Controller) *MockApprovalService {
	mock := &MockApprovalService{ctrl: ctrl}
	mock.recorder = &MockApprovalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalService) EXPECT() *MockApprovalServiceMockRecorder {
	return m.recorder
}

// ApproveTask mocks base method.
func (m *MockApprovalService) ApproveTask(c *gin.Context, taskId uint, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveTask", c, taskId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveTask indicates an expected call of ApproveTask.
func (mr *MockApprovalServiceMockRecorder) ApproveTask(c, taskId, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveTask", reflect.TypeOf((*MockApprovalService)(nil).ApproveTask), c, taskId, comment)
}

// BatchDelete mocks base method.
func (m *MockApprovalService) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalServiceMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalService)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockApprovalService) BatchUpdate(c *gin.Context, ids []uint, sysAppvoval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, sysAppvoval)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalServiceMockRecorder) BatchUpdate(c, ids, sysAppvoval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalService)(nil).BatchUpdate), c, ids, sysAppvoval)
}

// CanCancelFlow mocks base method.
func (m *MockApprovalService) CanCancelFlow(c *gin.Context, approvalCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanCancelFlow", c, approvalCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanCancelFlow indicates an expected call of CanCancelFlow.
func (mr *MockApprovalServiceMockRecorder) CanCancelFlow(c, approvalCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanCancelFlow", reflect.TypeOf((*MockApprovalService)(nil).CanCancelFlow), c, approvalCode)
}

// CanProcessFlow mocks base method.
func (m *MockApprovalService) CanProcessFlow(c *gin.Context, approvalCode, assigneeID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanProcessFlow", c, approvalCode, assigneeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanProcessFlow indicates an expected call of CanProcessFlow.
func (mr *MockApprovalServiceMockRecorder) CanProcessFlow(c, approvalCode, assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanProcessFlow", reflect.TypeOf((*MockApprovalService)(nil).CanProcessFlow), c, approvalCode, assigneeID)
}

// CheckExistingActiveDraft mocks base method.
func (m *MockApprovalService) CheckExistingActiveDraft(c *gin.Context, tableCodeDraft string, entityID any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistingActiveDraft", c, tableCodeDraft, entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckExistingActiveDraft indicates an expected call of CheckExistingActiveDraft.
func (mr *MockApprovalServiceMockRecorder) CheckExistingActiveDraft(c, tableCodeDraft, entityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistingActiveDraft", reflect.TypeOf((*MockApprovalService)(nil).CheckExistingActiveDraft), c, tableCodeDraft, entityID)
}

// CompleteApprovalFlow mocks base method.
func (m *MockApprovalService) CompleteApprovalFlow(c *gin.Context, approvalCode, result, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteApprovalFlow", c, approvalCode, result, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteApprovalFlow indicates an expected call of CompleteApprovalFlow.
func (mr *MockApprovalServiceMockRecorder) CompleteApprovalFlow(c, approvalCode, result, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteApprovalFlow", reflect.TypeOf((*MockApprovalService)(nil).CompleteApprovalFlow), c, approvalCode, result, reason)
}

// Create mocks base method.
func (m *MockApprovalService) Create(c *gin.Context, approval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, approval)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalServiceMockRecorder) Create(c, approval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalService)(nil).Create), c, approval)
}

// CreateApprovalFlow mocks base method.
func (m *MockApprovalService) CreateApprovalFlow(c *gin.Context, tableCode string, approvalInfo map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApprovalFlow", c, tableCode, approvalInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApprovalFlow indicates an expected call of CreateApprovalFlow.
func (mr *MockApprovalServiceMockRecorder) CreateApprovalFlow(c, tableCode, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApprovalFlow", reflect.TypeOf((*MockApprovalService)(nil).CreateApprovalFlow), c, tableCode, approvalInfo)
}

// CreateApprovalInstance mocks base method.
func (m *MockApprovalService) CreateApprovalInstance(c *gin.Context, approvalDefinition *model.ApprovalDefinition, approvalNodes []*model.ApprovalNode, approvalInfo map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApprovalInstance", c, approvalDefinition, approvalNodes, approvalInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApprovalInstance indicates an expected call of CreateApprovalInstance.
func (mr *MockApprovalServiceMockRecorder) CreateApprovalInstance(c, approvalDefinition, approvalNodes, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApprovalInstance", reflect.TypeOf((*MockApprovalService)(nil).CreateApprovalInstance), c, approvalDefinition, approvalNodes, approvalInfo)
}

// CreateApprovalTask mocks base method.
func (m *MockApprovalService) CreateApprovalTask(c *gin.Context, node *model.ApprovalNode, approvalInfo map[string]string) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApprovalTask", c, node, approvalInfo)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApprovalTask indicates an expected call of CreateApprovalTask.
func (mr *MockApprovalServiceMockRecorder) CreateApprovalTask(c, node, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApprovalTask", reflect.TypeOf((*MockApprovalService)(nil).CreateApprovalTask), c, node, approvalInfo)
}

// CreateDraftWithApproval mocks base method.
func (m *MockApprovalService) CreateDraftWithApproval(c *gin.Context, tableCode, reason string, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraftWithApproval", c, tableCode, reason, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDraftWithApproval indicates an expected call of CreateDraftWithApproval.
func (mr *MockApprovalServiceMockRecorder) CreateDraftWithApproval(c, tableCode, reason, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraftWithApproval", reflect.TypeOf((*MockApprovalService)(nil).CreateDraftWithApproval), c, tableCode, reason, entityMap)
}

// CreateStartTask mocks base method.
func (m *MockApprovalService) CreateStartTask(c *gin.Context, startNode *model.ApprovalNode, approvalInfo map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStartTask", c, startNode, approvalInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStartTask indicates an expected call of CreateStartTask.
func (mr *MockApprovalServiceMockRecorder) CreateStartTask(c, startNode, approvalInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStartTask", reflect.TypeOf((*MockApprovalService)(nil).CreateStartTask), c, startNode, approvalInfo)
}

// Delete mocks base method.
func (m *MockApprovalService) Delete(c *gin.Context, id uint) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalServiceMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalService)(nil).Delete), c, id)
}

// EvaluateConditionNode mocks base method.
func (m *MockApprovalService) EvaluateConditionNode(approvalNodes []*model.ApprovalNode, conditionNode *model.ApprovalNode, formData map[string]any) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateConditionNode", approvalNodes, conditionNode, formData)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateConditionNode indicates an expected call of EvaluateConditionNode.
func (mr *MockApprovalServiceMockRecorder) EvaluateConditionNode(approvalNodes, conditionNode, formData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateConditionNode", reflect.TypeOf((*MockApprovalService)(nil).EvaluateConditionNode), approvalNodes, conditionNode, formData)
}

// FindNodeByCode mocks base method.
func (m *MockApprovalService) FindNodeByCode(approvalNodes []*model.ApprovalNode, nodeCode string) *model.ApprovalNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNodeByCode", approvalNodes, nodeCode)
	ret0, _ := ret[0].(*model.ApprovalNode)
	return ret0
}

// FindNodeByCode indicates an expected call of FindNodeByCode.
func (mr *MockApprovalServiceMockRecorder) FindNodeByCode(approvalNodes, nodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNodeByCode", reflect.TypeOf((*MockApprovalService)(nil).FindNodeByCode), approvalNodes, nodeCode)
}

// FindPendingByAssignee mocks base method.
func (m *MockApprovalService) FindPendingByAssignee(assigneeName string, page, pageSize int, total *int64, timeRange string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByAssignee", assigneeName, page, pageSize, total, timeRange)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByAssignee indicates an expected call of FindPendingByAssignee.
func (mr *MockApprovalServiceMockRecorder) FindPendingByAssignee(assigneeName, page, pageSize, total, timeRange interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByAssignee", reflect.TypeOf((*MockApprovalService)(nil).FindPendingByAssignee), assigneeName, page, pageSize, total, timeRange)
}

// FindProcessedByAssignee mocks base method.
func (m *MockApprovalService) FindProcessedByAssignee(assigneeName string, page, pageSize int, total *int64, timeRange string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProcessedByAssignee", assigneeName, page, pageSize, total, timeRange)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProcessedByAssignee indicates an expected call of FindProcessedByAssignee.
func (mr *MockApprovalServiceMockRecorder) FindProcessedByAssignee(assigneeName, page, pageSize, total, timeRange interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProcessedByAssignee", reflect.TypeOf((*MockApprovalService)(nil).FindProcessedByAssignee), assigneeName, page, pageSize, total, timeRange)
}

// GenerateSerialNumber mocks base method.
func (m *MockApprovalService) GenerateSerialNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSerialNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSerialNumber indicates an expected call of GenerateSerialNumber.
func (mr *MockApprovalServiceMockRecorder) GenerateSerialNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSerialNumber", reflect.TypeOf((*MockApprovalService)(nil).GenerateSerialNumber))
}

// Get mocks base method.
func (m *MockApprovalService) Get(id uint) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApprovalServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApprovalService)(nil).Get), id)
}

// GetApprovalHistory mocks base method.
func (m *MockApprovalService) GetApprovalHistory(id uint) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovalHistory", id)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApprovalHistory indicates an expected call of GetApprovalHistory.
func (mr *MockApprovalServiceMockRecorder) GetApprovalHistory(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovalHistory", reflect.TypeOf((*MockApprovalService)(nil).GetApprovalHistory), id)
}

// GetApprovalStatisticsFlow mocks base method.
func (m *MockApprovalService) GetApprovalStatisticsFlow(applicantID string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovalStatisticsFlow", applicantID)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApprovalStatisticsFlow indicates an expected call of GetApprovalStatisticsFlow.
func (mr *MockApprovalServiceMockRecorder) GetApprovalStatisticsFlow(applicantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovalStatisticsFlow", reflect.TypeOf((*MockApprovalService)(nil).GetApprovalStatisticsFlow), applicantID)
}

// GetByApplicant mocks base method.
func (m *MockApprovalService) GetByApplicant(applicantID string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByApplicant", applicantID)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByApplicant indicates an expected call of GetByApplicant.
func (mr *MockApprovalServiceMockRecorder) GetByApplicant(applicantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByApplicant", reflect.TypeOf((*MockApprovalService)(nil).GetByApplicant), applicantID)
}

// GetByCode mocks base method.
func (m *MockApprovalService) GetByCode(code string) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", code)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockApprovalServiceMockRecorder) GetByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockApprovalService)(nil).GetByCode), code)
}

// GetByEntityCode mocks base method.
func (m *MockApprovalService) GetByEntityCode(entityCode string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEntityCode", entityCode)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEntityCode indicates an expected call of GetByEntityCode.
func (mr *MockApprovalServiceMockRecorder) GetByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEntityCode", reflect.TypeOf((*MockApprovalService)(nil).GetByEntityCode), entityCode)
}

// GetByEntityID mocks base method.
func (m *MockApprovalService) GetByEntityID(entityCode, entityID string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEntityID", entityCode, entityID)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEntityID indicates an expected call of GetByEntityID.
func (mr *MockApprovalServiceMockRecorder) GetByEntityID(entityCode, entityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEntityID", reflect.TypeOf((*MockApprovalService)(nil).GetByEntityID), entityCode, entityID)
}

// GetByStatus mocks base method.
func (m *MockApprovalService) GetByStatus(status string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", status)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockApprovalServiceMockRecorder) GetByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockApprovalService)(nil).GetByStatus), status)
}

// GetExpiredApprovalsFlow mocks base method.
func (m *MockApprovalService) GetExpiredApprovalsFlow() ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredApprovalsFlow")
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredApprovalsFlow indicates an expected call of GetExpiredApprovalsFlow.
func (mr *MockApprovalServiceMockRecorder) GetExpiredApprovalsFlow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredApprovalsFlow", reflect.TypeOf((*MockApprovalService)(nil).GetExpiredApprovalsFlow))
}

// GetNextApprovalNode mocks base method.
func (m *MockApprovalService) GetNextApprovalNode(approvalNodes []*model.ApprovalNode, currentNode *model.ApprovalNode, formData map[string]any) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextApprovalNode", approvalNodes, currentNode, formData)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextApprovalNode indicates an expected call of GetNextApprovalNode.
func (mr *MockApprovalServiceMockRecorder) GetNextApprovalNode(approvalNodes, currentNode, formData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextApprovalNode", reflect.TypeOf((*MockApprovalService)(nil).GetNextApprovalNode), approvalNodes, currentNode, formData)
}

// GetOperationInfo mocks base method.
func (m *MockApprovalService) GetOperationInfo(operation string, operationInfo *map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationInfo", operation, operationInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetOperationInfo indicates an expected call of GetOperationInfo.
func (mr *MockApprovalServiceMockRecorder) GetOperationInfo(operation, operationInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationInfo", reflect.TypeOf((*MockApprovalService)(nil).GetOperationInfo), operation, operationInfo)
}

// GetPendingByApplicant mocks base method.
func (m *MockApprovalService) GetPendingByApplicant(applicantID string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByApplicant", applicantID)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByApplicant indicates an expected call of GetPendingByApplicant.
func (mr *MockApprovalServiceMockRecorder) GetPendingByApplicant(applicantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByApplicant", reflect.TypeOf((*MockApprovalService)(nil).GetPendingByApplicant), applicantID)
}

// ImportWithApproval mocks base method.
func (m *MockApprovalService) ImportWithApproval(c *gin.Context, tableCode, reason, operation string, r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportWithApproval", c, tableCode, reason, operation, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportWithApproval indicates an expected call of ImportWithApproval.
func (mr *MockApprovalServiceMockRecorder) ImportWithApproval(c, tableCode, reason, operation, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportWithApproval", reflect.TypeOf((*MockApprovalService)(nil).ImportWithApproval), c, tableCode, reason, operation, r)
}

// List mocks base method.
func (m *MockApprovalService) List(page, pageSize int, total *int64, where map[string]any) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApprovalServiceMockRecorder) List(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApprovalService)(nil).List), page, pageSize, total, where)
}

// MoveToNextNodeFlow mocks base method.
func (m *MockApprovalService) MoveToNextNodeFlow(c *gin.Context, approvalCode, currentNodeCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToNextNodeFlow", c, approvalCode, currentNodeCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToNextNodeFlow indicates an expected call of MoveToNextNodeFlow.
func (mr *MockApprovalServiceMockRecorder) MoveToNextNodeFlow(c, approvalCode, currentNodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToNextNodeFlow", reflect.TypeOf((*MockApprovalService)(nil).MoveToNextNodeFlow), c, approvalCode, currentNodeCode)
}

// ParseApproverConfig mocks base method.
func (m *MockApprovalService) ParseApproverConfig(node *model.ApprovalNode, assigneeID, assigneeName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseApproverConfig", node, assigneeID, assigneeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseApproverConfig indicates an expected call of ParseApproverConfig.
func (mr *MockApprovalServiceMockRecorder) ParseApproverConfig(node, assigneeID, assigneeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseApproverConfig", reflect.TypeOf((*MockApprovalService)(nil).ParseApproverConfig), node, assigneeID, assigneeName)
}

// ProcessApprovalByCodeFlow mocks base method.
func (m *MockApprovalService) ProcessApprovalByCodeFlow(c *gin.Context, approvalCode, nodeCode, assigneeID, action, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessApprovalByCodeFlow", c, approvalCode, nodeCode, assigneeID, action, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessApprovalByCodeFlow indicates an expected call of ProcessApprovalByCodeFlow.
func (mr *MockApprovalServiceMockRecorder) ProcessApprovalByCodeFlow(c, approvalCode, nodeCode, assigneeID, action, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessApprovalByCodeFlow", reflect.TypeOf((*MockApprovalService)(nil).ProcessApprovalByCodeFlow), c, approvalCode, nodeCode, assigneeID, action, comment, reason)
}

// ProcessApprovalFlow mocks base method.
func (m *MockApprovalService) ProcessApprovalFlow(c *gin.Context, taskID uint, assigneeID, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessApprovalFlow", c, taskID, assigneeID, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessApprovalFlow indicates an expected call of ProcessApprovalFlow.
func (mr *MockApprovalServiceMockRecorder) ProcessApprovalFlow(c, taskID, assigneeID, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessApprovalFlow", reflect.TypeOf((*MockApprovalService)(nil).ProcessApprovalFlow), c, taskID, assigneeID, comment, reason)
}

// ProcessTask mocks base method.
func (m *MockApprovalService) ProcessTask(c *gin.Context, taskId uint, action, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", c, taskId, action, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockApprovalServiceMockRecorder) ProcessTask(c, taskId, action, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockApprovalService)(nil).ProcessTask), c, taskId, action, comment)
}

// RejectTask mocks base method.
func (m *MockApprovalService) RejectTask(c *gin.Context, taskId uint, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectTask", c, taskId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectTask indicates an expected call of RejectTask.
func (mr *MockApprovalServiceMockRecorder) RejectTask(c, taskId, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectTask", reflect.TypeOf((*MockApprovalService)(nil).RejectTask), c, taskId, comment)
}

// StartApproval mocks base method.
func (m *MockApprovalService) StartApproval(c *gin.Context, approvalDefCode, applicantID, title, formData string) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartApproval", c, approvalDefCode, applicantID, title, formData)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartApproval indicates an expected call of StartApproval.
func (mr *MockApprovalServiceMockRecorder) StartApproval(c, approvalDefCode, applicantID, title, formData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartApproval", reflect.TypeOf((*MockApprovalService)(nil).StartApproval), c, approvalDefCode, applicantID, title, formData)
}

// StartApprovalFlow mocks base method.
func (m *MockApprovalService) StartApprovalFlow(c *gin.Context, approvalDefCode, applicantID, title, formData string) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartApprovalFlow", c, approvalDefCode, applicantID, title, formData)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartApprovalFlow indicates an expected call of StartApprovalFlow.
func (mr *MockApprovalServiceMockRecorder) StartApprovalFlow(c, approvalDefCode, applicantID, title, formData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartApprovalFlow", reflect.TypeOf((*MockApprovalService)(nil).StartApprovalFlow), c, approvalDefCode, applicantID, title, formData)
}

// TransferTask mocks base method.
func (m *MockApprovalService) TransferTask(c *gin.Context, taskID uint, fromUserID, toUserID, fromUserName, toUserName, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTask", c, taskID, fromUserID, toUserID, fromUserName, toUserName, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferTask indicates an expected call of TransferTask.
func (mr *MockApprovalServiceMockRecorder) TransferTask(c, taskID, fromUserID, toUserID, fromUserName, toUserName, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTask", reflect.TypeOf((*MockApprovalService)(nil).TransferTask), c, taskID, fromUserID, toUserID, fromUserName, toUserName, reason)
}

// Update mocks base method.
func (m *MockApprovalService) Update(c *gin.Context, approval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, approval)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalServiceMockRecorder) Update(c, approval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalService)(nil).Update), c, approval)
}

// UpdateApprovalStatusFlow mocks base method.
func (m *MockApprovalService) UpdateApprovalStatusFlow(c *gin.Context, id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApprovalStatusFlow", c, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApprovalStatusFlow indicates an expected call of UpdateApprovalStatusFlow.
func (mr *MockApprovalServiceMockRecorder) UpdateApprovalStatusFlow(c, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApprovalStatusFlow", reflect.TypeOf((*MockApprovalService)(nil).UpdateApprovalStatusFlow), c, id, status)
}

// UpdateByIdsWithApproval mocks base method.
func (m *MockApprovalService) UpdateByIdsWithApproval(c *gin.Context, tableCode, reason string, ids []uint, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIdsWithApproval", c, tableCode, reason, ids, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByIdsWithApproval indicates an expected call of UpdateByIdsWithApproval.
func (mr *MockApprovalServiceMockRecorder) UpdateByIdsWithApproval(c, tableCode, reason, ids, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIdsWithApproval", reflect.TypeOf((*MockApprovalService)(nil).UpdateByIdsWithApproval), c, tableCode, reason, ids, entityMap)
}

// UpdateCurrentNodeFlow mocks base method.
func (m *MockApprovalService) UpdateCurrentNodeFlow(c *gin.Context, id uint, nodeID, nodeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentNodeFlow", c, id, nodeID, nodeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrentNodeFlow indicates an expected call of UpdateCurrentNodeFlow.
func (mr *MockApprovalServiceMockRecorder) UpdateCurrentNodeFlow(c, id, nodeID, nodeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrentNodeFlow", reflect.TypeOf((*MockApprovalService)(nil).UpdateCurrentNodeFlow), c, id, nodeID, nodeName)
}

// UpdateDraftWithApproval mocks base method.
func (m *MockApprovalService) UpdateDraftWithApproval(c *gin.Context, tableCode, reason string, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraftWithApproval", c, tableCode, reason, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDraftWithApproval indicates an expected call of UpdateDraftWithApproval.
func (mr *MockApprovalServiceMockRecorder) UpdateDraftWithApproval(c, tableCode, reason, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraftWithApproval", reflect.TypeOf((*MockApprovalService)(nil).UpdateDraftWithApproval), c, tableCode, reason, entityMap)
}

// ValidateApprovalFlow mocks base method.
func (m *MockApprovalService) ValidateApprovalFlow(c *gin.Context, approval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateApprovalFlow", c, approval)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateApprovalFlow indicates an expected call of ValidateApprovalFlow.
func (mr *MockApprovalServiceMockRecorder) ValidateApprovalFlow(c, approval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateApprovalFlow", reflect.TypeOf((*MockApprovalService)(nil).ValidateApprovalFlow), c, approval)
}
