// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/approval_task.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApprovalTaskService is a mock of ApprovalTaskService interface.
type MockApprovalTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalTaskServiceMockRecorder
}

// MockApprovalTaskServiceMockRecorder is the mock recorder for MockApprovalTaskService.
type MockApprovalTaskServiceMockRecorder struct {
	mock *MockApprovalTaskService
}

// NewMockApprovalTaskService creates a new mock instance.
func NewMockApprovalTaskService(ctrl *gomock.Controller) *MockApprovalTaskService {
	mock := &MockApprovalTaskService{ctrl: ctrl}
	mock.recorder = &MockApprovalTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalTaskService) EXPECT() *MockApprovalTaskServiceMockRecorder {
	return m.recorder
}

// ApproveTask mocks base method.
func (m *MockApprovalTaskService) ApproveTask(taskID uint, assigneeID, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveTask", taskID, assigneeID, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveTask indicates an expected call of ApproveTask.
func (mr *MockApprovalTaskServiceMockRecorder) ApproveTask(taskID, assigneeID, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveTask", reflect.TypeOf((*MockApprovalTaskService)(nil).ApproveTask), taskID, assigneeID, comment, reason)
}

// BatchDelete mocks base method.
func (m *MockApprovalTaskService) BatchDelete(ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalTaskServiceMockRecorder) BatchDelete(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalTaskService)(nil).BatchDelete), ids)
}

// BatchRemindTasks mocks base method.
func (m *MockApprovalTaskService) BatchRemindTasks(assigneeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRemindTasks", assigneeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRemindTasks indicates an expected call of BatchRemindTasks.
func (mr *MockApprovalTaskServiceMockRecorder) BatchRemindTasks(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRemindTasks", reflect.TypeOf((*MockApprovalTaskService)(nil).BatchRemindTasks), assigneeID)
}

// BatchUpdate mocks base method.
func (m *MockApprovalTaskService) BatchUpdate(ids []uint, approvalTask *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ids, approvalTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalTaskServiceMockRecorder) BatchUpdate(ids, approvalTask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalTaskService)(nil).BatchUpdate), ids, approvalTask)
}

// CanProcess mocks base method.
func (m *MockApprovalTaskService) CanProcess(taskID uint, assigneeID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanProcess", taskID, assigneeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanProcess indicates an expected call of CanProcess.
func (mr *MockApprovalTaskServiceMockRecorder) CanProcess(taskID, assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanProcess", reflect.TypeOf((*MockApprovalTaskService)(nil).CanProcess), taskID, assigneeID)
}

// CancelTask mocks base method.
func (m *MockApprovalTaskService) CancelTask(taskID uint, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTask", taskID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTask indicates an expected call of CancelTask.
func (mr *MockApprovalTaskServiceMockRecorder) CancelTask(taskID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTask", reflect.TypeOf((*MockApprovalTaskService)(nil).CancelTask), taskID, reason)
}

// CompleteTask mocks base method.
func (m *MockApprovalTaskService) CompleteTask(taskID uint, result, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTask", taskID, result, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTask indicates an expected call of CompleteTask.
func (mr *MockApprovalTaskServiceMockRecorder) CompleteTask(taskID, result, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTask", reflect.TypeOf((*MockApprovalTaskService)(nil).CompleteTask), taskID, result, comment, reason)
}

// Create mocks base method.
func (m *MockApprovalTaskService) Create(approvalTask *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", approvalTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalTaskServiceMockRecorder) Create(approvalTask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalTaskService)(nil).Create), approvalTask)
}

// Delete mocks base method.
func (m *MockApprovalTaskService) Delete(id uint) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalTaskServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalTaskService)(nil).Delete), id)
}

// First mocks base method.
func (m *MockApprovalTaskService) First(where map[string]any) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalTaskServiceMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalTaskService)(nil).First), where)
}

// Get mocks base method.
func (m *MockApprovalTaskService) Get(id uint) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApprovalTaskServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApprovalTaskService)(nil).Get), id)
}

// GetByApprovalCode mocks base method.
func (m *MockApprovalTaskService) GetByApprovalCode(approvalCode string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByApprovalCode", approvalCode)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByApprovalCode indicates an expected call of GetByApprovalCode.
func (mr *MockApprovalTaskServiceMockRecorder) GetByApprovalCode(approvalCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByApprovalCode", reflect.TypeOf((*MockApprovalTaskService)(nil).GetByApprovalCode), approvalCode)
}

// GetByAssignee mocks base method.
func (m *MockApprovalTaskService) GetByAssignee(assigneeID string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAssignee", assigneeID)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAssignee indicates an expected call of GetByAssignee.
func (mr *MockApprovalTaskServiceMockRecorder) GetByAssignee(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAssignee", reflect.TypeOf((*MockApprovalTaskService)(nil).GetByAssignee), assigneeID)
}

// GetByCode mocks base method.
func (m *MockApprovalTaskService) GetByCode(code string) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", code)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockApprovalTaskServiceMockRecorder) GetByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockApprovalTaskService)(nil).GetByCode), code)
}

// GetByNodeCode mocks base method.
func (m *MockApprovalTaskService) GetByNodeCode(nodeCode string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNodeCode", nodeCode)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNodeCode indicates an expected call of GetByNodeCode.
func (mr *MockApprovalTaskServiceMockRecorder) GetByNodeCode(nodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNodeCode", reflect.TypeOf((*MockApprovalTaskService)(nil).GetByNodeCode), nodeCode)
}

// GetByStatus mocks base method.
func (m *MockApprovalTaskService) GetByStatus(status string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", status)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockApprovalTaskServiceMockRecorder) GetByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockApprovalTaskService)(nil).GetByStatus), status)
}

// GetExpiredTasks mocks base method.
func (m *MockApprovalTaskService) GetExpiredTasks() ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredTasks")
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredTasks indicates an expected call of GetExpiredTasks.
func (mr *MockApprovalTaskServiceMockRecorder) GetExpiredTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredTasks", reflect.TypeOf((*MockApprovalTaskService)(nil).GetExpiredTasks))
}

// GetOverdueTasks mocks base method.
func (m *MockApprovalTaskService) GetOverdueTasks() ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverdueTasks")
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverdueTasks indicates an expected call of GetOverdueTasks.
func (mr *MockApprovalTaskServiceMockRecorder) GetOverdueTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverdueTasks", reflect.TypeOf((*MockApprovalTaskService)(nil).GetOverdueTasks))
}

// GetPendingByAssignee mocks base method.
func (m *MockApprovalTaskService) GetPendingByAssignee(assigneeID string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByAssignee", assigneeID)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByAssignee indicates an expected call of GetPendingByAssignee.
func (mr *MockApprovalTaskServiceMockRecorder) GetPendingByAssignee(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByAssignee", reflect.TypeOf((*MockApprovalTaskService)(nil).GetPendingByAssignee), assigneeID)
}

// GetTasksNeedRemind mocks base method.
func (m *MockApprovalTaskService) GetTasksNeedRemind() ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksNeedRemind")
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksNeedRemind indicates an expected call of GetTasksNeedRemind.
func (mr *MockApprovalTaskServiceMockRecorder) GetTasksNeedRemind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksNeedRemind", reflect.TypeOf((*MockApprovalTaskService)(nil).GetTasksNeedRemind))
}

// List mocks base method.
func (m *MockApprovalTaskService) List(page, pageSize int, total *int64, where map[string]any, order string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize, total, where, order)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApprovalTaskServiceMockRecorder) List(page, pageSize, total, where, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApprovalTaskService)(nil).List), page, pageSize, total, where, order)
}

// RejectTask mocks base method.
func (m *MockApprovalTaskService) RejectTask(taskID uint, assigneeID, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectTask", taskID, assigneeID, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectTask indicates an expected call of RejectTask.
func (mr *MockApprovalTaskServiceMockRecorder) RejectTask(taskID, assigneeID, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectTask", reflect.TypeOf((*MockApprovalTaskService)(nil).RejectTask), taskID, assigneeID, comment, reason)
}

// RemindTask mocks base method.
func (m *MockApprovalTaskService) RemindTask(taskID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemindTask", taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemindTask indicates an expected call of RemindTask.
func (mr *MockApprovalTaskServiceMockRecorder) RemindTask(taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemindTask", reflect.TypeOf((*MockApprovalTaskService)(nil).RemindTask), taskID)
}

// StartTask mocks base method.
func (m *MockApprovalTaskService) StartTask(taskID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTask", taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTask indicates an expected call of StartTask.
func (mr *MockApprovalTaskServiceMockRecorder) StartTask(taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTask", reflect.TypeOf((*MockApprovalTaskService)(nil).StartTask), taskID)
}

// TransferTask mocks base method.
func (m *MockApprovalTaskService) TransferTask(taskID uint, fromUserID, toUserID, fromUserName, toUserName, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTask", taskID, fromUserID, toUserID, fromUserName, toUserName, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferTask indicates an expected call of TransferTask.
func (mr *MockApprovalTaskServiceMockRecorder) TransferTask(taskID, fromUserID, toUserID, fromUserName, toUserName, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTask", reflect.TypeOf((*MockApprovalTaskService)(nil).TransferTask), taskID, fromUserID, toUserID, fromUserName, toUserName, reason)
}

// Update mocks base method.
func (m *MockApprovalTaskService) Update(approvalTask *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", approvalTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalTaskServiceMockRecorder) Update(approvalTask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalTaskService)(nil).Update), approvalTask)
}

// UpdateTaskStatus mocks base method.
func (m *MockApprovalTaskService) UpdateTaskStatus(taskID uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", taskID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockApprovalTaskServiceMockRecorder) UpdateTaskStatus(taskID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockApprovalTaskService)(nil).UpdateTaskStatus), taskID, status)
}

// ValidateTask mocks base method.
func (m *MockApprovalTaskService) ValidateTask(task *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTask", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTask indicates an expected call of ValidateTask.
func (mr *MockApprovalTaskServiceMockRecorder) ValidateTask(task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTask", reflect.TypeOf((*MockApprovalTaskService)(nil).ValidateTask), task)
}
