// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/approval_node.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApprovalNodeService is a mock of ApprovalNodeService interface.
type MockApprovalNodeService struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalNodeServiceMockRecorder
}

// MockApprovalNodeServiceMockRecorder is the mock recorder for MockApprovalNodeService.
type MockApprovalNodeServiceMockRecorder struct {
	mock *MockApprovalNodeService
}

// NewMockApprovalNodeService creates a new mock instance.
func NewMockApprovalNodeService(ctrl *gomock.Controller) *MockApprovalNodeService {
	mock := &MockApprovalNodeService{ctrl: ctrl}
	mock.recorder = &MockApprovalNodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalNodeService) EXPECT() *MockApprovalNodeServiceMockRecorder {
	return m.recorder
}

// ActivateNode mocks base method.
func (m *MockApprovalNodeService) ActivateNode(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateNode", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateNode indicates an expected call of ActivateNode.
func (mr *MockApprovalNodeServiceMockRecorder) ActivateNode(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateNode", reflect.TypeOf((*MockApprovalNodeService)(nil).ActivateNode), id)
}

// BatchDelete mocks base method.
func (m *MockApprovalNodeService) BatchDelete(ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalNodeServiceMockRecorder) BatchDelete(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalNodeService)(nil).BatchDelete), ids)
}

// BatchSyncNodes mocks base method.
func (m *MockApprovalNodeService) BatchSyncNodes(approvalDefCode string, nodes []*model.ApprovalNode) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSyncNodes", approvalDefCode, nodes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchSyncNodes indicates an expected call of BatchSyncNodes.
func (mr *MockApprovalNodeServiceMockRecorder) BatchSyncNodes(approvalDefCode, nodes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSyncNodes", reflect.TypeOf((*MockApprovalNodeService)(nil).BatchSyncNodes), approvalDefCode, nodes)
}

// BatchUpdate mocks base method.
func (m *MockApprovalNodeService) BatchUpdate(ids []uint, approvalNode *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ids, approvalNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalNodeServiceMockRecorder) BatchUpdate(ids, approvalNode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalNodeService)(nil).BatchUpdate), ids, approvalNode)
}

// CanDeleteNode mocks base method.
func (m *MockApprovalNodeService) CanDeleteNode(id uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDeleteNode", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanDeleteNode indicates an expected call of CanDeleteNode.
func (mr *MockApprovalNodeServiceMockRecorder) CanDeleteNode(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDeleteNode", reflect.TypeOf((*MockApprovalNodeService)(nil).CanDeleteNode), id)
}

// ConfigureApprovers mocks base method.
func (m *MockApprovalNodeService) ConfigureApprovers(nodeId uint, approverConfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureApprovers", nodeId, approverConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureApprovers indicates an expected call of ConfigureApprovers.
func (mr *MockApprovalNodeServiceMockRecorder) ConfigureApprovers(nodeId, approverConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureApprovers", reflect.TypeOf((*MockApprovalNodeService)(nil).ConfigureApprovers), nodeId, approverConfig)
}

// ConfigureConditions mocks base method.
func (m *MockApprovalNodeService) ConfigureConditions(nodeId uint, conditionConfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureConditions", nodeId, conditionConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureConditions indicates an expected call of ConfigureConditions.
func (mr *MockApprovalNodeServiceMockRecorder) ConfigureConditions(nodeId, conditionConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureConditions", reflect.TypeOf((*MockApprovalNodeService)(nil).ConfigureConditions), nodeId, conditionConfig)
}

// ConfigureTimeouts mocks base method.
func (m *MockApprovalNodeService) ConfigureTimeouts(nodeId uint, timeoutHours int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureTimeouts", nodeId, timeoutHours)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureTimeouts indicates an expected call of ConfigureTimeouts.
func (mr *MockApprovalNodeServiceMockRecorder) ConfigureTimeouts(nodeId, timeoutHours interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureTimeouts", reflect.TypeOf((*MockApprovalNodeService)(nil).ConfigureTimeouts), nodeId, timeoutHours)
}

// Create mocks base method.
func (m *MockApprovalNodeService) Create(approvalNode *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", approvalNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalNodeServiceMockRecorder) Create(approvalNode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalNodeService)(nil).Create), approvalNode)
}

// DeactivateNode mocks base method.
func (m *MockApprovalNodeService) DeactivateNode(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateNode", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateNode indicates an expected call of DeactivateNode.
func (mr *MockApprovalNodeServiceMockRecorder) DeactivateNode(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateNode", reflect.TypeOf((*MockApprovalNodeService)(nil).DeactivateNode), id)
}

// Delete mocks base method.
func (m *MockApprovalNodeService) Delete(id uint) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalNodeServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalNodeService)(nil).Delete), id)
}

// First mocks base method.
func (m *MockApprovalNodeService) First(where map[string]any) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalNodeServiceMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalNodeService)(nil).First), where)
}

// Get mocks base method.
func (m *MockApprovalNodeService) Get(id uint) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApprovalNodeServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApprovalNodeService)(nil).Get), id)
}

// GetActiveByApprovalDefCode mocks base method.
func (m *MockApprovalNodeService) GetActiveByApprovalDefCode(approvalDefCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByApprovalDefCode", approvalDefCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByApprovalDefCode indicates an expected call of GetActiveByApprovalDefCode.
func (mr *MockApprovalNodeServiceMockRecorder) GetActiveByApprovalDefCode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByApprovalDefCode", reflect.TypeOf((*MockApprovalNodeService)(nil).GetActiveByApprovalDefCode), approvalDefCode)
}

// GetByApprovalDefCode mocks base method.
func (m *MockApprovalNodeService) GetByApprovalDefCode(approvalDefCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByApprovalDefCode", approvalDefCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByApprovalDefCode indicates an expected call of GetByApprovalDefCode.
func (mr *MockApprovalNodeServiceMockRecorder) GetByApprovalDefCode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByApprovalDefCode", reflect.TypeOf((*MockApprovalNodeService)(nil).GetByApprovalDefCode), approvalDefCode)
}

// GetByCode mocks base method.
func (m *MockApprovalNodeService) GetByCode(code string) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", code)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockApprovalNodeServiceMockRecorder) GetByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockApprovalNodeService)(nil).GetByCode), code)
}

// GetByNodeType mocks base method.
func (m *MockApprovalNodeService) GetByNodeType(nodeType string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNodeType", nodeType)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNodeType indicates an expected call of GetByNodeType.
func (mr *MockApprovalNodeServiceMockRecorder) GetByNodeType(nodeType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNodeType", reflect.TypeOf((*MockApprovalNodeService)(nil).GetByNodeType), nodeType)
}

// GetEndNodes mocks base method.
func (m *MockApprovalNodeService) GetEndNodes(approvalDefCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndNodes", approvalDefCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEndNodes indicates an expected call of GetEndNodes.
func (mr *MockApprovalNodeServiceMockRecorder) GetEndNodes(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndNodes", reflect.TypeOf((*MockApprovalNodeService)(nil).GetEndNodes), approvalDefCode)
}

// GetNextNodes mocks base method.
func (m *MockApprovalNodeService) GetNextNodes(approvalDefCode, currentNodeCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextNodes", approvalDefCode, currentNodeCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextNodes indicates an expected call of GetNextNodes.
func (mr *MockApprovalNodeServiceMockRecorder) GetNextNodes(approvalDefCode, currentNodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextNodes", reflect.TypeOf((*MockApprovalNodeService)(nil).GetNextNodes), approvalDefCode, currentNodeCode)
}

// GetStartNode mocks base method.
func (m *MockApprovalNodeService) GetStartNode(approvalDefCode string) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStartNode", approvalDefCode)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStartNode indicates an expected call of GetStartNode.
func (mr *MockApprovalNodeServiceMockRecorder) GetStartNode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStartNode", reflect.TypeOf((*MockApprovalNodeService)(nil).GetStartNode), approvalDefCode)
}

// List mocks base method.
func (m *MockApprovalNodeService) List(page, pageSize int, total *int64, where map[string]any) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApprovalNodeServiceMockRecorder) List(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApprovalNodeService)(nil).List), page, pageSize, total, where)
}

// Update mocks base method.
func (m *MockApprovalNodeService) Update(approvalNode *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", approvalNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalNodeServiceMockRecorder) Update(approvalNode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalNodeService)(nil).Update), approvalNode)
}

// ValidateNode mocks base method.
func (m *MockApprovalNodeService) ValidateNode(node *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateNode", node)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateNode indicates an expected call of ValidateNode.
func (mr *MockApprovalNodeServiceMockRecorder) ValidateNode(node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateNode", reflect.TypeOf((*MockApprovalNodeService)(nil).ValidateNode), node)
}

// ValidateWorkflow mocks base method.
func (m *MockApprovalNodeService) ValidateWorkflow(approvalDefCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWorkflow", approvalDefCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWorkflow indicates an expected call of ValidateWorkflow.
func (mr *MockApprovalNodeServiceMockRecorder) ValidateWorkflow(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWorkflow", reflect.TypeOf((*MockApprovalNodeService)(nil).ValidateWorkflow), approvalDefCode)
}
