// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/autocode.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAutocodeService is a mock of AutocodeService interface.
type MockAutocodeService struct {
	ctrl     *gomock.Controller
	recorder *MockAutocodeServiceMockRecorder
}

// MockAutocodeServiceMockRecorder is the mock recorder for MockAutocodeService.
type MockAutocodeServiceMockRecorder struct {
	mock *MockAutocodeService
}

// NewMockAutocodeService creates a new mock instance.
func NewMockAutocodeService(ctrl *gomock.Controller) *MockAutocodeService {
	mock := &MockAutocodeService{ctrl: ctrl}
	mock.recorder = &MockAutocodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutocodeService) EXPECT() *MockAutocodeServiceMockRecorder {
	return m.recorder
}

// GenerateCode mocks base method.
func (m *MockAutocodeService) GenerateCode(tableCode, fieldCode string, patterns []model.SequencePattern, entityMap map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCode", tableCode, fieldCode, patterns, entityMap)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCode indicates an expected call of GenerateCode.
func (mr *MockAutocodeServiceMockRecorder) GenerateCode(tableCode, fieldCode, patterns, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCode", reflect.TypeOf((*MockAutocodeService)(nil).GenerateCode), tableCode, fieldCode, patterns, entityMap)
}
