// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/entity_log.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockEntityLogService is a mock of EntityLogService interface.
type MockEntityLogService struct {
	ctrl     *gomock.Controller
	recorder *MockEntityLogServiceMockRecorder
}

// MockEntityLogServiceMockRecorder is the mock recorder for MockEntityLogService.
type MockEntityLogServiceMockRecorder struct {
	mock *MockEntityLogService
}

// NewMockEntityLogService creates a new mock instance.
func NewMockEntityLogService(ctrl *gomock.Controller) *MockEntityLogService {
	mock := &MockEntityLogService{ctrl: ctrl}
	mock.recorder = &MockEntityLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityLogService) EXPECT() *MockEntityLogServiceMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockEntityLogService) BatchDelete(c *gin.Context, tableCode string, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, tableCode, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockEntityLogServiceMockRecorder) BatchDelete(c, tableCode, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockEntityLogService)(nil).BatchDelete), c, tableCode, ids)
}

// BatchUpdate mocks base method.
func (m *MockEntityLogService) BatchUpdate(c *gin.Context, tableCode string, ids []uint, entityLog *model.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, tableCode, ids, entityLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockEntityLogServiceMockRecorder) BatchUpdate(c, tableCode, ids, entityLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockEntityLogService)(nil).BatchUpdate), c, tableCode, ids, entityLog)
}

// Create mocks base method.
func (m *MockEntityLogService) Create(c *gin.Context, tableCode string, entityLog *model.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, tableCode, entityLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEntityLogServiceMockRecorder) Create(c, tableCode, entityLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntityLogService)(nil).Create), c, tableCode, entityLog)
}

// Delete mocks base method.
func (m *MockEntityLogService) Delete(c *gin.Context, tableCode string, id uint) (*model.EntityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, tableCode, id)
	ret0, _ := ret[0].(*model.EntityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockEntityLogServiceMockRecorder) Delete(c, tableCode, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEntityLogService)(nil).Delete), c, tableCode, id)
}

// Get mocks base method.
func (m *MockEntityLogService) Get(tableCode string, id uint) (*model.EntityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tableCode, id)
	ret0, _ := ret[0].(*model.EntityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEntityLogServiceMockRecorder) Get(tableCode, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEntityLogService)(nil).Get), tableCode, id)
}

// List mocks base method.
func (m *MockEntityLogService) List(tableCode string, page, pageSize int, total *int64, where map[string]any) ([]*model.EntityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tableCode, page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.EntityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEntityLogServiceMockRecorder) List(tableCode, page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEntityLogService)(nil).List), tableCode, page, pageSize, total, where)
}

// Update mocks base method.
func (m *MockEntityLogService) Update(c *gin.Context, tableCode string, entityLog *model.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, tableCode, entityLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEntityLogServiceMockRecorder) Update(c, tableCode, entityLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEntityLogService)(nil).Update), c, tableCode, entityLog)
}
