// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/global_id.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGlobalIdService is a mock of GlobalIdService interface.
type MockGlobalIdService struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalIdServiceMockRecorder
}

// MockGlobalIdServiceMockRecorder is the mock recorder for MockGlobalIdService.
type MockGlobalIdServiceMockRecorder struct {
	mock *MockGlobalIdService
}

// NewMockGlobalIdService creates a new mock instance.
func NewMockGlobalIdService(ctrl *gomock.Controller) *MockGlobalIdService {
	mock := &MockGlobalIdService{ctrl: ctrl}
	mock.recorder = &MockGlobalIdServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalIdService) EXPECT() *MockGlobalIdServiceMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockGlobalIdService) BatchDelete(ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockGlobalIdServiceMockRecorder) BatchDelete(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockGlobalIdService)(nil).BatchDelete), ids)
}

// BatchUpdate mocks base method.
func (m *MockGlobalIdService) BatchUpdate(ids []uint, globalId *model.GlobalId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ids, globalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockGlobalIdServiceMockRecorder) BatchUpdate(ids, globalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockGlobalIdService)(nil).BatchUpdate), ids, globalId)
}

// Create mocks base method.
func (m *MockGlobalIdService) Create(globalId *model.GlobalId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", globalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGlobalIdServiceMockRecorder) Create(globalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGlobalIdService)(nil).Create), globalId)
}

// Delete mocks base method.
func (m *MockGlobalIdService) Delete(id uint) (*model.GlobalId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.GlobalId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockGlobalIdServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGlobalIdService)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockGlobalIdService) Get(id uint) (*model.GlobalId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.GlobalId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGlobalIdServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGlobalIdService)(nil).Get), id)
}

// GetNewID mocks base method.
func (m *MockGlobalIdService) GetNewID(identifier string) uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewID", identifier)
	ret0, _ := ret[0].(uint)
	return ret0
}

// GetNewID indicates an expected call of GetNewID.
func (mr *MockGlobalIdServiceMockRecorder) GetNewID(identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewID", reflect.TypeOf((*MockGlobalIdService)(nil).GetNewID), identifier)
}

// List mocks base method.
func (m *MockGlobalIdService) List(page, pageSize int, total *int64, where map[string]any) ([]*model.GlobalId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.GlobalId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGlobalIdServiceMockRecorder) List(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGlobalIdService)(nil).List), page, pageSize, total, where)
}

// Update mocks base method.
func (m *MockGlobalIdService) Update(globalId *model.GlobalId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", globalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGlobalIdServiceMockRecorder) Update(globalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGlobalIdService)(nil).Update), globalId)
}
