// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/table_field.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockTableFieldService is a mock of TableFieldService interface.
type MockTableFieldService struct {
	ctrl     *gomock.Controller
	recorder *MockTableFieldServiceMockRecorder
}

// MockTableFieldServiceMockRecorder is the mock recorder for MockTableFieldService.
type MockTableFieldServiceMockRecorder struct {
	mock *MockTableFieldService
}

// NewMockTableFieldService creates a new mock instance.
func NewMockTableFieldService(ctrl *gomock.Controller) *MockTableFieldService {
	mock := &MockTableFieldService{ctrl: ctrl}
	mock.recorder = &MockTableFieldServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableFieldService) EXPECT() *MockTableFieldServiceMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockTableFieldService) BatchCreate(c *gin.Context, fields []*model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", c, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockTableFieldServiceMockRecorder) BatchCreate(c, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockTableFieldService)(nil).BatchCreate), c, fields)
}

// BatchDelete mocks base method.
func (m *MockTableFieldService) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockTableFieldServiceMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockTableFieldService)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockTableFieldService) BatchUpdate(c *gin.Context, ids []uint, tableField *model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, tableField)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockTableFieldServiceMockRecorder) BatchUpdate(c, ids, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockTableFieldService)(nil).BatchUpdate), c, ids, tableField)
}

// Create mocks base method.
func (m *MockTableFieldService) Create(c *gin.Context, tableField *model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, tableField)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTableFieldServiceMockRecorder) Create(c, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTableFieldService)(nil).Create), c, tableField)
}

// Delete mocks base method.
func (m *MockTableFieldService) Delete(c *gin.Context, id uint) (*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTableFieldServiceMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTableFieldService)(nil).Delete), c, id)
}

// Find mocks base method.
func (m *MockTableFieldService) Find(sel string, where map[string]any) ([]*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", sel, where)
	ret0, _ := ret[0].([]*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTableFieldServiceMockRecorder) Find(sel, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTableFieldService)(nil).Find), sel, where)
}

// Get mocks base method.
func (m *MockTableFieldService) Get(id uint) (*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTableFieldServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTableFieldService)(nil).Get), id)
}

// GetTableFields mocks base method.
func (m *MockTableFieldService) GetTableFields(tableCode string) ([]*model.FieldMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableFields", tableCode)
	ret0, _ := ret[0].([]*model.FieldMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableFields indicates an expected call of GetTableFields.
func (mr *MockTableFieldServiceMockRecorder) GetTableFields(tableCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableFields", reflect.TypeOf((*MockTableFieldService)(nil).GetTableFields), tableCode)
}

// GetTableOptions mocks base method.
func (m *MockTableFieldService) GetTableOptions(tableCode string, filter map[string]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableOptions", tableCode, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableOptions indicates an expected call of GetTableOptions.
func (mr *MockTableFieldServiceMockRecorder) GetTableOptions(tableCode, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableOptions", reflect.TypeOf((*MockTableFieldService)(nil).GetTableOptions), tableCode, filter)
}

// List mocks base method.
func (m *MockTableFieldService) List(page, pageSize int, total *int64, where map[string]any) ([]*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTableFieldServiceMockRecorder) List(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTableFieldService)(nil).List), page, pageSize, total, where)
}

// Public mocks base method.
func (m *MockTableFieldService) Public(c *gin.Context, tableCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Public", c, tableCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Public indicates an expected call of Public.
func (mr *MockTableFieldServiceMockRecorder) Public(c, tableCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Public", reflect.TypeOf((*MockTableFieldService)(nil).Public), c, tableCode)
}

// Update mocks base method.
func (m *MockTableFieldService) Update(c *gin.Context, tableField *model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, tableField)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTableFieldServiceMockRecorder) Update(c, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTableFieldService)(nil).Update), c, tableField)
}
