/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * OpenAPIApi - axios parameter creator
 * @export
 */
export const OpenAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 通过 OpenAPI 查询指定实体的列表数据
         * @summary 查询实体列表 (OpenAPI)
         * @param {string} table 实体表名
         * @param {number} [page] 页码
         * @param {number} [pageSize] 每页数量
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiV1EntitiesTableGet: async (table: string, page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'table' is not null or undefined
            assertParamExists('openapiV1EntitiesTableGet', 'table', table)
            const localVarPath = `/openapi/v1/entities/{table}`
                .replace(`{${"table"}}`, encodeURIComponent(String(table)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 通过 OpenAPI 查询指定实体的详情数据
         * @summary 查询实体详情 (OpenAPI)
         * @param {string} table 实体表名
         * @param {number} id 记录 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiV1EntitiesTableIdGet: async (table: string, id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'table' is not null or undefined
            assertParamExists('openapiV1EntitiesTableIdGet', 'table', table)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('openapiV1EntitiesTableIdGet', 'id', id)
            const localVarPath = `/openapi/v1/entities/{table}/{id}`
                .replace(`{${"table"}}`, encodeURIComponent(String(table)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenAPIApi - functional programming interface
 * @export
 */
export const OpenAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 通过 OpenAPI 查询指定实体的列表数据
         * @summary 查询实体列表 (OpenAPI)
         * @param {string} table 实体表名
         * @param {number} [page] 页码
         * @param {number} [pageSize] 每页数量
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openapiV1EntitiesTableGet(table: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openapiV1EntitiesTableGet(table, page, pageSize, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OpenAPIApi.openapiV1EntitiesTableGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 通过 OpenAPI 查询指定实体的详情数据
         * @summary 查询实体详情 (OpenAPI)
         * @param {string} table 实体表名
         * @param {number} id 记录 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openapiV1EntitiesTableIdGet(table: string, id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openapiV1EntitiesTableIdGet(table, id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OpenAPIApi.openapiV1EntitiesTableIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * OpenAPIApi - factory interface
 * @export
 */
export const OpenAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenAPIApiFp(configuration)
    return {
        /**
         * 通过 OpenAPI 查询指定实体的列表数据
         * @summary 查询实体列表 (OpenAPI)
         * @param {OpenAPIApiOpenapiV1EntitiesTableGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiV1EntitiesTableGet(requestParameters: OpenAPIApiOpenapiV1EntitiesTableGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.openapiV1EntitiesTableGet(requestParameters.table, requestParameters.page, requestParameters.pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 通过 OpenAPI 查询指定实体的详情数据
         * @summary 查询实体详情 (OpenAPI)
         * @param {OpenAPIApiOpenapiV1EntitiesTableIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiV1EntitiesTableIdGet(requestParameters: OpenAPIApiOpenapiV1EntitiesTableIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.openapiV1EntitiesTableIdGet(requestParameters.table, requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for openapiV1EntitiesTableGet operation in OpenAPIApi.
 * @export
 * @interface OpenAPIApiOpenapiV1EntitiesTableGetRequest
 */
export interface OpenAPIApiOpenapiV1EntitiesTableGetRequest {
    /**
     * 实体表名
     * @type {string}
     * @memberof OpenAPIApiOpenapiV1EntitiesTableGet
     */
    readonly table: string

    /**
     * 页码
     * @type {number}
     * @memberof OpenAPIApiOpenapiV1EntitiesTableGet
     */
    readonly page?: number

    /**
     * 每页数量
     * @type {number}
     * @memberof OpenAPIApiOpenapiV1EntitiesTableGet
     */
    readonly pageSize?: number
}

/**
 * Request parameters for openapiV1EntitiesTableIdGet operation in OpenAPIApi.
 * @export
 * @interface OpenAPIApiOpenapiV1EntitiesTableIdGetRequest
 */
export interface OpenAPIApiOpenapiV1EntitiesTableIdGetRequest {
    /**
     * 实体表名
     * @type {string}
     * @memberof OpenAPIApiOpenapiV1EntitiesTableIdGet
     */
    readonly table: string

    /**
     * 记录 ID
     * @type {number}
     * @memberof OpenAPIApiOpenapiV1EntitiesTableIdGet
     */
    readonly id: number
}

/**
 * OpenAPIApi - object-oriented interface
 * @export
 * @class OpenAPIApi
 * @extends {BaseAPI}
 */
export class OpenAPIApi extends BaseAPI {
    /**
     * 通过 OpenAPI 查询指定实体的列表数据
     * @summary 查询实体列表 (OpenAPI)
     * @param {OpenAPIApiOpenapiV1EntitiesTableGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenAPIApi
     */
    public openapiV1EntitiesTableGet(requestParameters: OpenAPIApiOpenapiV1EntitiesTableGetRequest, options?: RawAxiosRequestConfig) {
        return OpenAPIApiFp(this.configuration).openapiV1EntitiesTableGet(requestParameters.table, requestParameters.page, requestParameters.pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 通过 OpenAPI 查询指定实体的详情数据
     * @summary 查询实体详情 (OpenAPI)
     * @param {OpenAPIApiOpenapiV1EntitiesTableIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenAPIApi
     */
    public openapiV1EntitiesTableIdGet(requestParameters: OpenAPIApiOpenapiV1EntitiesTableIdGetRequest, options?: RawAxiosRequestConfig) {
        return OpenAPIApiFp(this.configuration).openapiV1EntitiesTableIdGet(requestParameters.table, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

