/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { PiemdmInternalModelWebhook } from '../models';
// @ts-ignore
import { PiemdmInternalModelWebhookDelivery } from '../models';
/**
 * WebhookApi - axios parameter creator
 * @export
 */
export const WebhookApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 批量删除Webhook投递记录
         * @param {object} data 批量删除请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesBatchDelete: async (data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhookDeliveriesBatchDelete', 'data', data)
            const localVarPath = `/admin/webhook_deliveries/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 批量更新Webhook投递记录
         * @param {object} data 批量更新请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesBatchPut: async (data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhookDeliveriesBatchPut', 'data', data)
            const localVarPath = `/admin/webhook_deliveries/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取Webhook投递记录列表
         * @param {number} [page] 页码
         * @param {number} [pageSize] 每页数量
         * @param {string} [deliveryCode] 投递代码
         * @param {string} [tableCode] 表代码
         * @param {string} [entityId] 实体ID
         * @param {string} [startDate] 开始日期
         * @param {string} [endDate] 结束日期
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesGet: async (page?: number, pageSize?: number, deliveryCode?: string, tableCode?: string, entityId?: string, startDate?: string, endDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/webhook_deliveries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (deliveryCode !== undefined) {
                localVarQueryParameter['deliveryCode'] = deliveryCode;
            }

            if (tableCode !== undefined) {
                localVarQueryParameter['table_code'] = tableCode;
            }

            if (entityId !== undefined) {
                localVarQueryParameter['entity_id'] = entityId;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除Webhook投递记录
         * @param {number} id 投递记录ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminWebhookDeliveriesIdDelete', 'id', id)
            const localVarPath = `/admin/webhook_deliveries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取Webhook投递记录详情
         * @param {number} id 投递记录ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminWebhookDeliveriesIdGet', 'id', id)
            const localVarPath = `/admin/webhook_deliveries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新Webhook投递记录
         * @param {number} id 投递记录ID
         * @param {object} data 投递记录信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesIdPut: async (id: number, data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminWebhookDeliveriesIdPut', 'id', id)
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhookDeliveriesIdPut', 'data', data)
            const localVarPath = `/admin/webhook_deliveries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 创建Webhook投递记录
         * @param {object} data 投递记录信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesPost: async (data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhookDeliveriesPost', 'data', data)
            const localVarPath = `/admin/webhook_deliveries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 批量删除Webhook
         * @param {object} data 批量删除请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksBatchDelete: async (data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhooksBatchDelete', 'data', data)
            const localVarPath = `/admin/webhooks/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 批量更新Webhook状态
         * @param {object} data 批量更新请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksBatchPut: async (data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhooksBatchPut', 'data', data)
            const localVarPath = `/admin/webhooks/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取Webhook列表
         * @param {number} [page] 页码
         * @param {number} [pageSize] 每页数量
         * @param {string} [tableCode] 表代码
         * @param {string} [startDate] 开始日期
         * @param {string} [endDate] 结束日期
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksGet: async (page?: number, pageSize?: number, tableCode?: string, startDate?: string, endDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/webhooks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (tableCode !== undefined) {
                localVarQueryParameter['tableCode'] = tableCode;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除Webhook
         * @param {number} id WebhookID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminWebhooksIdDelete', 'id', id)
            const localVarPath = `/admin/webhooks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取Webhook详情
         * @param {number} id WebhookID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminWebhooksIdGet', 'id', id)
            const localVarPath = `/admin/webhooks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新Webhook
         * @param {number} id WebhookID
         * @param {object} data Webhook信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksIdPut: async (id: number, data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminWebhooksIdPut', 'id', id)
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhooksIdPut', 'data', data)
            const localVarPath = `/admin/webhooks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 创建Webhook
         * @param {object} data Webhook信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksPost: async (data: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('adminWebhooksPost', 'data', data)
            const localVarPath = `/admin/webhooks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebhookApi - functional programming interface
 * @export
 */
export const WebhookApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebhookApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 批量删除Webhook投递记录
         * @param {object} data 批量删除请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesBatchDelete(data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesBatchDelete(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesBatchDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 批量更新Webhook投递记录
         * @param {object} data 批量更新请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesBatchPut(data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesBatchPut(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesBatchPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 获取Webhook投递记录列表
         * @param {number} [page] 页码
         * @param {number} [pageSize] 每页数量
         * @param {string} [deliveryCode] 投递代码
         * @param {string} [tableCode] 表代码
         * @param {string} [entityId] 实体ID
         * @param {string} [startDate] 开始日期
         * @param {string} [endDate] 结束日期
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesGet(page?: number, pageSize?: number, deliveryCode?: string, tableCode?: string, entityId?: string, startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PiemdmInternalModelWebhookDelivery>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesGet(page, pageSize, deliveryCode, tableCode, entityId, startDate, endDate, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 删除Webhook投递记录
         * @param {number} id 投递记录ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesIdDelete(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 获取Webhook投递记录详情
         * @param {number} id 投递记录ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PiemdmInternalModelWebhookDelivery>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesIdGet(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 更新Webhook投递记录
         * @param {number} id 投递记录ID
         * @param {object} data 投递记录信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesIdPut(id: number, data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesIdPut(id, data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 创建Webhook投递记录
         * @param {object} data 投递记录信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhookDeliveriesPost(data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PiemdmInternalModelWebhookDelivery>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhookDeliveriesPost(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhookDeliveriesPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 批量删除Webhook
         * @param {object} data 批量删除请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksBatchDelete(data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksBatchDelete(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksBatchDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 批量更新Webhook状态
         * @param {object} data 批量更新请求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksBatchPut(data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksBatchPut(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksBatchPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 获取Webhook列表
         * @param {number} [page] 页码
         * @param {number} [pageSize] 每页数量
         * @param {string} [tableCode] 表代码
         * @param {string} [startDate] 开始日期
         * @param {string} [endDate] 结束日期
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksGet(page?: number, pageSize?: number, tableCode?: string, startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PiemdmInternalModelWebhook>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksGet(page, pageSize, tableCode, startDate, endDate, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 删除Webhook
         * @param {number} id WebhookID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksIdDelete(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 获取Webhook详情
         * @param {number} id WebhookID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PiemdmInternalModelWebhook>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksIdGet(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 更新Webhook
         * @param {number} id WebhookID
         * @param {object} data Webhook信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksIdPut(id: number, data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksIdPut(id, data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 创建Webhook
         * @param {object} data Webhook信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminWebhooksPost(data: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PiemdmInternalModelWebhook>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminWebhooksPost(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebhookApi.adminWebhooksPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * WebhookApi - factory interface
 * @export
 */
export const WebhookApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebhookApiFp(configuration)
    return {
        /**
         * 
         * @summary 批量删除Webhook投递记录
         * @param {WebhookApiAdminWebhookDeliveriesBatchDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesBatchDelete(requestParameters: WebhookApiAdminWebhookDeliveriesBatchDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhookDeliveriesBatchDelete(requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 批量更新Webhook投递记录
         * @param {WebhookApiAdminWebhookDeliveriesBatchPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesBatchPut(requestParameters: WebhookApiAdminWebhookDeliveriesBatchPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhookDeliveriesBatchPut(requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取Webhook投递记录列表
         * @param {WebhookApiAdminWebhookDeliveriesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesGet(requestParameters: WebhookApiAdminWebhookDeliveriesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<PiemdmInternalModelWebhookDelivery>> {
            return localVarFp.adminWebhookDeliveriesGet(requestParameters.page, requestParameters.pageSize, requestParameters.deliveryCode, requestParameters.tableCode, requestParameters.entityId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除Webhook投递记录
         * @param {WebhookApiAdminWebhookDeliveriesIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesIdDelete(requestParameters: WebhookApiAdminWebhookDeliveriesIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhookDeliveriesIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取Webhook投递记录详情
         * @param {WebhookApiAdminWebhookDeliveriesIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesIdGet(requestParameters: WebhookApiAdminWebhookDeliveriesIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PiemdmInternalModelWebhookDelivery> {
            return localVarFp.adminWebhookDeliveriesIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新Webhook投递记录
         * @param {WebhookApiAdminWebhookDeliveriesIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesIdPut(requestParameters: WebhookApiAdminWebhookDeliveriesIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhookDeliveriesIdPut(requestParameters.id, requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 创建Webhook投递记录
         * @param {WebhookApiAdminWebhookDeliveriesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhookDeliveriesPost(requestParameters: WebhookApiAdminWebhookDeliveriesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<PiemdmInternalModelWebhookDelivery> {
            return localVarFp.adminWebhookDeliveriesPost(requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 批量删除Webhook
         * @param {WebhookApiAdminWebhooksBatchDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksBatchDelete(requestParameters: WebhookApiAdminWebhooksBatchDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhooksBatchDelete(requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 批量更新Webhook状态
         * @param {WebhookApiAdminWebhooksBatchPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksBatchPut(requestParameters: WebhookApiAdminWebhooksBatchPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhooksBatchPut(requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取Webhook列表
         * @param {WebhookApiAdminWebhooksGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksGet(requestParameters: WebhookApiAdminWebhooksGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<PiemdmInternalModelWebhook>> {
            return localVarFp.adminWebhooksGet(requestParameters.page, requestParameters.pageSize, requestParameters.tableCode, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除Webhook
         * @param {WebhookApiAdminWebhooksIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksIdDelete(requestParameters: WebhookApiAdminWebhooksIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhooksIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取Webhook详情
         * @param {WebhookApiAdminWebhooksIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksIdGet(requestParameters: WebhookApiAdminWebhooksIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PiemdmInternalModelWebhook> {
            return localVarFp.adminWebhooksIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新Webhook
         * @param {WebhookApiAdminWebhooksIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksIdPut(requestParameters: WebhookApiAdminWebhooksIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adminWebhooksIdPut(requestParameters.id, requestParameters.data, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 创建Webhook
         * @param {WebhookApiAdminWebhooksPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminWebhooksPost(requestParameters: WebhookApiAdminWebhooksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<PiemdmInternalModelWebhook> {
            return localVarFp.adminWebhooksPost(requestParameters.data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for adminWebhookDeliveriesBatchDelete operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesBatchDeleteRequest
 */
export interface WebhookApiAdminWebhookDeliveriesBatchDeleteRequest {
    /**
     * 批量删除请求
     * @type {object}
     * @memberof WebhookApiAdminWebhookDeliveriesBatchDelete
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhookDeliveriesBatchPut operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesBatchPutRequest
 */
export interface WebhookApiAdminWebhookDeliveriesBatchPutRequest {
    /**
     * 批量更新请求
     * @type {object}
     * @memberof WebhookApiAdminWebhookDeliveriesBatchPut
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhookDeliveriesGet operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesGetRequest
 */
export interface WebhookApiAdminWebhookDeliveriesGetRequest {
    /**
     * 页码
     * @type {number}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly page?: number

    /**
     * 每页数量
     * @type {number}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly pageSize?: number

    /**
     * 投递代码
     * @type {string}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly deliveryCode?: string

    /**
     * 表代码
     * @type {string}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly tableCode?: string

    /**
     * 实体ID
     * @type {string}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly entityId?: string

    /**
     * 开始日期
     * @type {string}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly startDate?: string

    /**
     * 结束日期
     * @type {string}
     * @memberof WebhookApiAdminWebhookDeliveriesGet
     */
    readonly endDate?: string
}

/**
 * Request parameters for adminWebhookDeliveriesIdDelete operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesIdDeleteRequest
 */
export interface WebhookApiAdminWebhookDeliveriesIdDeleteRequest {
    /**
     * 投递记录ID
     * @type {number}
     * @memberof WebhookApiAdminWebhookDeliveriesIdDelete
     */
    readonly id: number
}

/**
 * Request parameters for adminWebhookDeliveriesIdGet operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesIdGetRequest
 */
export interface WebhookApiAdminWebhookDeliveriesIdGetRequest {
    /**
     * 投递记录ID
     * @type {number}
     * @memberof WebhookApiAdminWebhookDeliveriesIdGet
     */
    readonly id: number
}

/**
 * Request parameters for adminWebhookDeliveriesIdPut operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesIdPutRequest
 */
export interface WebhookApiAdminWebhookDeliveriesIdPutRequest {
    /**
     * 投递记录ID
     * @type {number}
     * @memberof WebhookApiAdminWebhookDeliveriesIdPut
     */
    readonly id: number

    /**
     * 投递记录信息
     * @type {object}
     * @memberof WebhookApiAdminWebhookDeliveriesIdPut
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhookDeliveriesPost operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhookDeliveriesPostRequest
 */
export interface WebhookApiAdminWebhookDeliveriesPostRequest {
    /**
     * 投递记录信息
     * @type {object}
     * @memberof WebhookApiAdminWebhookDeliveriesPost
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhooksBatchDelete operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksBatchDeleteRequest
 */
export interface WebhookApiAdminWebhooksBatchDeleteRequest {
    /**
     * 批量删除请求
     * @type {object}
     * @memberof WebhookApiAdminWebhooksBatchDelete
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhooksBatchPut operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksBatchPutRequest
 */
export interface WebhookApiAdminWebhooksBatchPutRequest {
    /**
     * 批量更新请求
     * @type {object}
     * @memberof WebhookApiAdminWebhooksBatchPut
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhooksGet operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksGetRequest
 */
export interface WebhookApiAdminWebhooksGetRequest {
    /**
     * 页码
     * @type {number}
     * @memberof WebhookApiAdminWebhooksGet
     */
    readonly page?: number

    /**
     * 每页数量
     * @type {number}
     * @memberof WebhookApiAdminWebhooksGet
     */
    readonly pageSize?: number

    /**
     * 表代码
     * @type {string}
     * @memberof WebhookApiAdminWebhooksGet
     */
    readonly tableCode?: string

    /**
     * 开始日期
     * @type {string}
     * @memberof WebhookApiAdminWebhooksGet
     */
    readonly startDate?: string

    /**
     * 结束日期
     * @type {string}
     * @memberof WebhookApiAdminWebhooksGet
     */
    readonly endDate?: string
}

/**
 * Request parameters for adminWebhooksIdDelete operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksIdDeleteRequest
 */
export interface WebhookApiAdminWebhooksIdDeleteRequest {
    /**
     * WebhookID
     * @type {number}
     * @memberof WebhookApiAdminWebhooksIdDelete
     */
    readonly id: number
}

/**
 * Request parameters for adminWebhooksIdGet operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksIdGetRequest
 */
export interface WebhookApiAdminWebhooksIdGetRequest {
    /**
     * WebhookID
     * @type {number}
     * @memberof WebhookApiAdminWebhooksIdGet
     */
    readonly id: number
}

/**
 * Request parameters for adminWebhooksIdPut operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksIdPutRequest
 */
export interface WebhookApiAdminWebhooksIdPutRequest {
    /**
     * WebhookID
     * @type {number}
     * @memberof WebhookApiAdminWebhooksIdPut
     */
    readonly id: number

    /**
     * Webhook信息
     * @type {object}
     * @memberof WebhookApiAdminWebhooksIdPut
     */
    readonly data: object
}

/**
 * Request parameters for adminWebhooksPost operation in WebhookApi.
 * @export
 * @interface WebhookApiAdminWebhooksPostRequest
 */
export interface WebhookApiAdminWebhooksPostRequest {
    /**
     * Webhook信息
     * @type {object}
     * @memberof WebhookApiAdminWebhooksPost
     */
    readonly data: object
}

/**
 * WebhookApi - object-oriented interface
 * @export
 * @class WebhookApi
 * @extends {BaseAPI}
 */
export class WebhookApi extends BaseAPI {
    /**
     * 
     * @summary 批量删除Webhook投递记录
     * @param {WebhookApiAdminWebhookDeliveriesBatchDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesBatchDelete(requestParameters: WebhookApiAdminWebhookDeliveriesBatchDeleteRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesBatchDelete(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 批量更新Webhook投递记录
     * @param {WebhookApiAdminWebhookDeliveriesBatchPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesBatchPut(requestParameters: WebhookApiAdminWebhookDeliveriesBatchPutRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesBatchPut(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取Webhook投递记录列表
     * @param {WebhookApiAdminWebhookDeliveriesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesGet(requestParameters: WebhookApiAdminWebhookDeliveriesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesGet(requestParameters.page, requestParameters.pageSize, requestParameters.deliveryCode, requestParameters.tableCode, requestParameters.entityId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除Webhook投递记录
     * @param {WebhookApiAdminWebhookDeliveriesIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesIdDelete(requestParameters: WebhookApiAdminWebhookDeliveriesIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取Webhook投递记录详情
     * @param {WebhookApiAdminWebhookDeliveriesIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesIdGet(requestParameters: WebhookApiAdminWebhookDeliveriesIdGetRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新Webhook投递记录
     * @param {WebhookApiAdminWebhookDeliveriesIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesIdPut(requestParameters: WebhookApiAdminWebhookDeliveriesIdPutRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesIdPut(requestParameters.id, requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 创建Webhook投递记录
     * @param {WebhookApiAdminWebhookDeliveriesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhookDeliveriesPost(requestParameters: WebhookApiAdminWebhookDeliveriesPostRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhookDeliveriesPost(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 批量删除Webhook
     * @param {WebhookApiAdminWebhooksBatchDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksBatchDelete(requestParameters: WebhookApiAdminWebhooksBatchDeleteRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksBatchDelete(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 批量更新Webhook状态
     * @param {WebhookApiAdminWebhooksBatchPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksBatchPut(requestParameters: WebhookApiAdminWebhooksBatchPutRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksBatchPut(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取Webhook列表
     * @param {WebhookApiAdminWebhooksGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksGet(requestParameters: WebhookApiAdminWebhooksGetRequest = {}, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksGet(requestParameters.page, requestParameters.pageSize, requestParameters.tableCode, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除Webhook
     * @param {WebhookApiAdminWebhooksIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksIdDelete(requestParameters: WebhookApiAdminWebhooksIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取Webhook详情
     * @param {WebhookApiAdminWebhooksIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksIdGet(requestParameters: WebhookApiAdminWebhooksIdGetRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新Webhook
     * @param {WebhookApiAdminWebhooksIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksIdPut(requestParameters: WebhookApiAdminWebhooksIdPutRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksIdPut(requestParameters.id, requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 创建Webhook
     * @param {WebhookApiAdminWebhooksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhookApi
     */
    public adminWebhooksPost(requestParameters: WebhookApiAdminWebhooksPostRequest, options?: RawAxiosRequestConfig) {
        return WebhookApiFp(this.configuration).adminWebhooksPost(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }
}

