// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"piemdm/internal/handler"
	"piemdm/internal/pkg/casbin"
	"piemdm/internal/pkg/transaction"
	"piemdm/internal/repository"
	"piemdm/internal/server"
	"piemdm/internal/service"
	"piemdm/pkg/cron"
	"piemdm/pkg/cron/job"
	"piemdm/pkg/helper/sid"
	"piemdm/pkg/jwt"
	"piemdm/pkg/log"
	"piemdm/pkg/notification"
	"piemdm/pkg/webhook"
	"piemdm/pkg/webhook/task"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*server.Server, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	serviceService := service.NewService(logger, sidSid, jwtJWT)
	db := repository.NewDB(viperViper)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	base := repository.NewBaseRepository(repositoryRepository)
	tableFieldRepository := repository.NewTableFieldRepository(repositoryRepository, base)
	entityRepository := repository.NewEntityRepository(repositoryRepository, base, tableFieldRepository)
	tableRepository := repository.NewTableRepository(repositoryRepository, base)
	tableFieldService := service.NewTableFieldService(serviceService, tableFieldRepository, tableRepository)
	tableApprovalDefinitionRepository := repository.NewTableApprovalDefinitionRepository(repositoryRepository, base)
	approvalRepository := repository.NewApprovalRepository(repositoryRepository, base)
	approvalTaskRepository := repository.NewApprovalTaskRepository(repositoryRepository, base)
	approvalTaskService := service.NewApprovalTaskService(serviceService, approvalTaskRepository, approvalRepository)
	approvalDefinitionRepository := repository.NewApprovalDefinitionRepository(repositoryRepository, base)
	approvalNodeRepository := repository.NewApprovalNodeRepository(repositoryRepository, base)
	approvalDefinitionService := service.NewApprovalDefinitionService(serviceService, approvalDefinitionRepository, approvalNodeRepository)
	approvalNodeService := service.NewApprovalNodeService(serviceService, approvalNodeRepository, approvalDefinitionRepository)
	entityLogRepository := repository.NewEntityLogRepository(repositoryRepository, base)
	entityLogService := service.NewEntityLogService(serviceService, entityLogRepository)
	webhookRepository := repository.NewWebhookRepository(repositoryRepository, base)
	webhookService := service.NewWebhookService(serviceService, webhookRepository)
	globalIdRepository := repository.NewGlobalIdRepository(repositoryRepository, base)
	globalIdService := service.NewGlobalIdService(serviceService, globalIdRepository)
	userRepository := repository.NewUserRepository(repositoryRepository, base)
	notificationService := notification.NewNotificationServiceProvider(viperViper, logger)
	approvalService := service.NewApprovalService(serviceService, approvalRepository, approvalTaskService, approvalDefinitionService, approvalNodeService, entityRepository, tableFieldService, entityLogService, webhookService, tableFieldRepository, approvalDefinitionRepository, tableApprovalDefinitionRepository, approvalNodeRepository, globalIdService, approvalTaskRepository, userRepository, notificationService)
	autocodeService := service.NewAutocodeService(serviceService, globalIdService)
	tablePermissionRepository := repository.NewTablePermissionRepository(db)
	userRoleRepository := repository.NewUserRoleRepository(db)
	tablePermissionService := service.NewTablePermissionService(tablePermissionRepository, tableRepository, userRoleRepository)
	entityService := service.NewEntityService(serviceService, entityRepository, tableFieldService, tableFieldRepository, tableApprovalDefinitionRepository, approvalService, globalIdService, entityLogService, autocodeService, tablePermissionService, tableRepository, viperViper)
	tableApprovalDefinitionService := service.NewTableApprovalDefinitionService(serviceService, tableApprovalDefinitionRepository)
	entityHandler := handler.NewEntityHandler(handlerHandler, entityService, tableFieldService, tableApprovalDefinitionService, tablePermissionService, viperViper)
	approvalHandler := handler.NewApprovalHandler(handlerHandler, approvalService)
	approvalDefinitionHandler := handler.NewApprovalDefinitionHandler(handlerHandler, approvalDefinitionService)
	approvalNodeHandler := handler.NewApprovalNodeHandler(handlerHandler, approvalNodeService)
	approvalTaskHandler := handler.NewApprovalTaskHandler(handlerHandler, approvalTaskService, approvalService)
	tableService := service.NewTableService(serviceService, tableRepository, tableFieldRepository)
	tableHandler := handler.NewTableHandler(handlerHandler, tableService, tablePermissionService)
	tableFieldHandler := handler.NewTableFieldHandler(handlerHandler, tableFieldService)
	applicationRepository := repository.NewApplicationRepository(repositoryRepository, base)
	applicationService := service.NewApplicationService(serviceService, applicationRepository)
	applicationHandler := handler.NewApplicationHandler(handlerHandler, applicationService)
	webhookHandler := handler.NewWebhookHandler(handlerHandler, webhookService)
	webhookDeliveryRepository := repository.NewWebhookDeliveryRepository(repositoryRepository, base)
	webhookDeliveryService := service.NewWebhookDeliveryService(serviceService, webhookDeliveryRepository)
	webhookDeliveryHandler := handler.NewWebhookDeliveryHandler(handlerHandler, webhookDeliveryService, tablePermissionService)
	cronRepository := repository.NewCronRepository(repositoryRepository, base)
	cronService := service.NewCronService(serviceService, cronRepository)
	cronHandler := handler.NewCronHandler(handlerHandler, cronService)
	cronLogRepository := repository.NewCronLogRepository(repositoryRepository, base)
	cronLogService := service.NewCronLogService(serviceService, cronLogRepository)
	cronLogHandler := handler.NewCronLogHandler(handlerHandler, cronLogService)
	roleRepository := repository.NewRoleRepository(repositoryRepository, base)
	enforcer, err := casbin.InitEnforcer(db)
	if err != nil {
		return nil, nil, err
	}
	roleService := service.NewRoleService(serviceService, roleRepository, userRoleRepository, enforcer)
	roleHandler := handler.NewRoleHandler(handlerHandler, roleService)
	permissionRepository := repository.NewPermissionRepository(db, logger)
	permissionService := service.NewPermissionService(permissionRepository, logger)
	permissionHandler := handler.NewPermissionHandler(handlerHandler, permissionService)
	userService := service.NewUserService(logger, sidSid, jwtJWT, client, userRepository, userRoleRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService, roleService, jwtJWT)
	notificationTemplateRepository := repository.NewNotificationTemplateRepository(db)
	notificationTemplateService := service.NewNotificationTemplateService(notificationTemplateRepository, logger)
	notificationLogRepository := repository.NewNotificationLogRepository(db)
	serviceNotificationService := service.NewNotificationService(notificationTemplateService, notificationLogRepository, logger)
	notificationHandler := handler.NewNotificationHandler(handlerHandler, serviceNotificationService)
	transactionManager := transaction.NewTransactionManager(db, logger)
	notificationTemplateHandler := handler.NewNotificationTemplateHandler(handlerHandler, notificationTemplateService, transactionManager)
	notificationLogService := service.NewNotificationLogService(notificationLogRepository, logger)
	notificationLogHandler := handler.NewNotificationLogHandler(handlerHandler, notificationLogService)
	tableApprovalDefinitionHandler := handler.NewTableApprovalDefinitionHandler(handlerHandler, tableApprovalDefinitionService)
	uploadService := service.NewUploadService()
	uploadHandler := handler.NewUploadHandler(handlerHandler, uploadService)
	tablePermissionHandler := handler.NewTablePermissionHandler(handlerHandler, tablePermissionService)
	openApiHandler := handler.NewOpenApiHandler(logger, entityService, entityRepository)
	applicationEntityRepository := repository.NewApplicationEntityRepository(repositoryRepository, base)
	applicationApiLogRepository := repository.NewApplicationApiLogRepository(repositoryRepository, base)
	engine := server.NewServerHTTP(logger, jwtJWT, entityHandler, approvalHandler, approvalDefinitionHandler, approvalNodeHandler, approvalTaskHandler, tableHandler, tableFieldHandler, applicationHandler, webhookHandler, webhookDeliveryHandler, cronHandler, cronLogHandler, roleHandler, permissionHandler, userHandler, notificationHandler, notificationTemplateHandler, notificationLogHandler, tableApprovalDefinitionHandler, uploadHandler, tablePermissionHandler, openApiHandler, applicationRepository, applicationEntityRepository, applicationApiLogRepository, client, viperViper, enforcer)
	serverServer := server.NewServer(engine, notificationHandler)
	return serverServer, func() {
	}, nil
}

func newCronApp(viperViper *viper.Viper, logger *log.Logger) (*cron.Cron, func(), error) {
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJwt(viperViper)
	client := repository.NewRedis(viperViper)
	db := repository.NewDB(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	base := repository.NewBaseRepository(repositoryRepository)
	userRepository := repository.NewUserRepository(repositoryRepository, base)
	userRoleRepository := repository.NewUserRoleRepository(db)
	userService := service.NewUserService(logger, sidSid, jwtJWT, client, userRepository, userRoleRepository)
	serviceService := service.NewService(logger, sidSid, jwtJWT)
	cronRepository := repository.NewCronRepository(repositoryRepository, base)
	cronService := service.NewCronService(serviceService, cronRepository)
	scanner := job.NewScanner(userService, cronService)
	cronParamRepository := repository.NewCronParamRepository(repositoryRepository, base)
	cronParamService := service.NewCronParamService(serviceService, cronParamRepository)
	tableFieldRepository := repository.NewTableFieldRepository(repositoryRepository, base)
	entityRepository := repository.NewEntityRepository(repositoryRepository, base, tableFieldRepository)
	tableRepository := repository.NewTableRepository(repositoryRepository, base)
	tableFieldService := service.NewTableFieldService(serviceService, tableFieldRepository, tableRepository)
	tableApprovalDefinitionRepository := repository.NewTableApprovalDefinitionRepository(repositoryRepository, base)
	approvalRepository := repository.NewApprovalRepository(repositoryRepository, base)
	approvalTaskRepository := repository.NewApprovalTaskRepository(repositoryRepository, base)
	approvalTaskService := service.NewApprovalTaskService(serviceService, approvalTaskRepository, approvalRepository)
	approvalDefinitionRepository := repository.NewApprovalDefinitionRepository(repositoryRepository, base)
	approvalNodeRepository := repository.NewApprovalNodeRepository(repositoryRepository, base)
	approvalDefinitionService := service.NewApprovalDefinitionService(serviceService, approvalDefinitionRepository, approvalNodeRepository)
	approvalNodeService := service.NewApprovalNodeService(serviceService, approvalNodeRepository, approvalDefinitionRepository)
	entityLogRepository := repository.NewEntityLogRepository(repositoryRepository, base)
	entityLogService := service.NewEntityLogService(serviceService, entityLogRepository)
	webhookRepository := repository.NewWebhookRepository(repositoryRepository, base)
	webhookService := service.NewWebhookService(serviceService, webhookRepository)
	globalIdRepository := repository.NewGlobalIdRepository(repositoryRepository, base)
	globalIdService := service.NewGlobalIdService(serviceService, globalIdRepository)
	notificationService := notification.NewNotificationServiceProvider(viperViper, logger)
	approvalService := service.NewApprovalService(serviceService, approvalRepository, approvalTaskService, approvalDefinitionService, approvalNodeService, entityRepository, tableFieldService, entityLogService, webhookService, tableFieldRepository, approvalDefinitionRepository, tableApprovalDefinitionRepository, approvalNodeRepository, globalIdService, approvalTaskRepository, userRepository, notificationService)
	autocodeService := service.NewAutocodeService(serviceService, globalIdService)
	tablePermissionRepository := repository.NewTablePermissionRepository(db)
	tablePermissionService := service.NewTablePermissionService(tablePermissionRepository, tableRepository, userRoleRepository)
	entityService := service.NewEntityService(serviceService, entityRepository, tableFieldService, tableFieldRepository, tableApprovalDefinitionRepository, approvalService, globalIdService, entityLogService, autocodeService, tablePermissionService, tableRepository, viperViper)
	cronCron := cron.NewCron(scanner, cronService, cronParamService, entityService)
	return cronCron, func() {
	}, nil
}

func newWebhookApp(viperViper *viper.Viper, logger *log.Logger) (*webhook.Webhook, func(), error) {
	client := repository.NewRedis(viperViper)
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJwt(viperViper)
	serviceService := service.NewService(logger, sidSid, jwtJWT)
	db := repository.NewDB(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	base := repository.NewBaseRepository(repositoryRepository)
	webhookRepository := repository.NewWebhookRepository(repositoryRepository, base)
	webhookService := service.NewWebhookService(serviceService, webhookRepository)
	tableFieldRepository := repository.NewTableFieldRepository(repositoryRepository, base)
	entityRepository := repository.NewEntityRepository(repositoryRepository, base, tableFieldRepository)
	tableRepository := repository.NewTableRepository(repositoryRepository, base)
	tableFieldService := service.NewTableFieldService(serviceService, tableFieldRepository, tableRepository)
	tableApprovalDefinitionRepository := repository.NewTableApprovalDefinitionRepository(repositoryRepository, base)
	approvalRepository := repository.NewApprovalRepository(repositoryRepository, base)
	approvalTaskRepository := repository.NewApprovalTaskRepository(repositoryRepository, base)
	approvalTaskService := service.NewApprovalTaskService(serviceService, approvalTaskRepository, approvalRepository)
	approvalDefinitionRepository := repository.NewApprovalDefinitionRepository(repositoryRepository, base)
	approvalNodeRepository := repository.NewApprovalNodeRepository(repositoryRepository, base)
	approvalDefinitionService := service.NewApprovalDefinitionService(serviceService, approvalDefinitionRepository, approvalNodeRepository)
	approvalNodeService := service.NewApprovalNodeService(serviceService, approvalNodeRepository, approvalDefinitionRepository)
	entityLogRepository := repository.NewEntityLogRepository(repositoryRepository, base)
	entityLogService := service.NewEntityLogService(serviceService, entityLogRepository)
	globalIdRepository := repository.NewGlobalIdRepository(repositoryRepository, base)
	globalIdService := service.NewGlobalIdService(serviceService, globalIdRepository)
	userRepository := repository.NewUserRepository(repositoryRepository, base)
	notificationService := notification.NewNotificationServiceProvider(viperViper, logger)
	approvalService := service.NewApprovalService(serviceService, approvalRepository, approvalTaskService, approvalDefinitionService, approvalNodeService, entityRepository, tableFieldService, entityLogService, webhookService, tableFieldRepository, approvalDefinitionRepository, tableApprovalDefinitionRepository, approvalNodeRepository, globalIdService, approvalTaskRepository, userRepository, notificationService)
	autocodeService := service.NewAutocodeService(serviceService, globalIdService)
	tablePermissionRepository := repository.NewTablePermissionRepository(db)
	userRoleRepository := repository.NewUserRoleRepository(db)
	tablePermissionService := service.NewTablePermissionService(tablePermissionRepository, tableRepository, userRoleRepository)
	entityService := service.NewEntityService(serviceService, entityRepository, tableFieldService, tableFieldRepository, tableApprovalDefinitionRepository, approvalService, globalIdService, entityLogService, autocodeService, tablePermissionService, tableRepository, viperViper)
	webhookDeliveryRepository := repository.NewWebhookDeliveryRepository(repositoryRepository, base)
	webhookDeliveryService := service.NewWebhookDeliveryService(serviceService, webhookDeliveryRepository)
	scanner := task.NewScanner(client, webhookService, entityService, webhookDeliveryService)
	webhookWebhook := webhook.NewWebhook(scanner)
	return webhookWebhook, func() {
	}, nil
}

// wire.go:

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewApprovalHandler, handler.NewApprovalDefinitionHandler, handler.NewApprovalNodeHandler, handler.NewApprovalTaskHandler, handler.NewTableHandler, handler.NewTableFieldHandler, handler.NewApplicationHandler, handler.NewWebhookHandler, handler.NewWebhookDeliveryHandler, handler.NewCronHandler, handler.NewCronLogHandler, handler.NewEntityHandler, handler.NewRoleHandler, handler.NewPermissionHandler, handler.NewNotificationHandler, handler.NewNotificationTemplateHandler, handler.NewNotificationLogHandler, handler.NewTableApprovalDefinitionHandler, handler.NewUploadHandler, handler.NewTablePermissionHandler, handler.NewOpenApiHandler)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewApprovalService, service.NewApprovalDefinitionService, service.NewApprovalNodeService, service.NewApprovalTaskService, service.NewTableService, service.NewTableFieldService, service.NewApplicationService, service.NewWebhookService, service.NewWebhookDeliveryService, service.NewCronService, service.NewCronLogService, service.NewCronParamService, service.NewEntityService, service.NewEntityLogService, service.NewGlobalIdService, service.NewRoleService, service.NewPermissionService, service.NewNotificationService, service.NewNotificationTemplateService, service.NewNotificationLogService, service.NewTableApprovalDefinitionService, service.NewAutocodeService, service.NewUploadService, service.NewTablePermissionService, service.NewOpenApiAuthService, service.NewApplicationApiLogService)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewBaseRepository, repository.NewUserRepository, repository.NewApprovalRepository, repository.NewApprovalDefinitionRepository, repository.NewApprovalNodeRepository, repository.NewApprovalTaskRepository, repository.NewTableRepository, repository.NewTableFieldRepository, repository.NewApplicationRepository, repository.NewWebhookRepository, repository.NewWebhookDeliveryRepository, repository.NewCronRepository, repository.NewCronParamRepository, repository.NewCronLogRepository, repository.NewEntityRepository, repository.NewEntityLogRepository, repository.NewGlobalIdRepository, repository.NewRoleRepository, repository.NewPermissionRepository, repository.NewNotificationTemplateRepository, repository.NewNotificationLogRepository, repository.NewTableApprovalDefinitionRepository, repository.NewTablePermissionRepository, repository.NewUserRoleRepository, repository.NewApplicationApiLogRepository, repository.NewApplicationEntityRepository)

var CasbinSet = wire.NewSet(casbin.InitEnforcer)

var CronSet = wire.NewSet(job.NewScanner, cron.NewCron)

var WebhookSet = wire.NewSet(task.NewScanner, webhook.NewWebhook)

var TransactionSet = wire.NewSet(transaction.NewTransactionManager)

var NotificationSet = wire.NewSet(notification.NewNotificationServiceProvider)
