// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/approval_node.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApprovalNodeRepository is a mock of ApprovalNodeRepository interface.
type MockApprovalNodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalNodeRepositoryMockRecorder
}

// MockApprovalNodeRepositoryMockRecorder is the mock recorder for MockApprovalNodeRepository.
type MockApprovalNodeRepositoryMockRecorder struct {
	mock *MockApprovalNodeRepository
}

// NewMockApprovalNodeRepository creates a new mock instance.
func NewMockApprovalNodeRepository(ctrl *gomock.Controller) *MockApprovalNodeRepository {
	mock := &MockApprovalNodeRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalNodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalNodeRepository) EXPECT() *MockApprovalNodeRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockApprovalNodeRepository) BatchDelete(ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalNodeRepositoryMockRecorder) BatchDelete(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalNodeRepository)(nil).BatchDelete), ids)
}

// BatchUpdate mocks base method.
func (m *MockApprovalNodeRepository) BatchUpdate(ids []uint, approvalNode *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ids, approvalNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalNodeRepositoryMockRecorder) BatchUpdate(ids, approvalNode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalNodeRepository)(nil).BatchUpdate), ids, approvalNode)
}

// CountByApprovalDefCode mocks base method.
func (m *MockApprovalNodeRepository) CountByApprovalDefCode(approvalDefCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByApprovalDefCode", approvalDefCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByApprovalDefCode indicates an expected call of CountByApprovalDefCode.
func (mr *MockApprovalNodeRepositoryMockRecorder) CountByApprovalDefCode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByApprovalDefCode", reflect.TypeOf((*MockApprovalNodeRepository)(nil).CountByApprovalDefCode), approvalDefCode)
}

// CountByNodeType mocks base method.
func (m *MockApprovalNodeRepository) CountByNodeType(nodeType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByNodeType", nodeType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByNodeType indicates an expected call of CountByNodeType.
func (mr *MockApprovalNodeRepositoryMockRecorder) CountByNodeType(nodeType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByNodeType", reflect.TypeOf((*MockApprovalNodeRepository)(nil).CountByNodeType), nodeType)
}

// Create mocks base method.
func (m *MockApprovalNodeRepository) Create(approvalNode *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", approvalNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalNodeRepositoryMockRecorder) Create(approvalNode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalNodeRepository)(nil).Create), approvalNode)
}

// Delete mocks base method.
func (m *MockApprovalNodeRepository) Delete(id uint) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalNodeRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalNodeRepository)(nil).Delete), id)
}

// FindActiveByApprovalDefCode mocks base method.
func (m *MockApprovalNodeRepository) FindActiveByApprovalDefCode(approvalDefCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByApprovalDefCode", approvalDefCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByApprovalDefCode indicates an expected call of FindActiveByApprovalDefCode.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindActiveByApprovalDefCode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByApprovalDefCode", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindActiveByApprovalDefCode), approvalDefCode)
}

// FindByApprovalDefCode mocks base method.
func (m *MockApprovalNodeRepository) FindByApprovalDefCode(approvalDefCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByApprovalDefCode", approvalDefCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByApprovalDefCode indicates an expected call of FindByApprovalDefCode.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindByApprovalDefCode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByApprovalDefCode", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindByApprovalDefCode), approvalDefCode)
}

// FindByNodeType mocks base method.
func (m *MockApprovalNodeRepository) FindByNodeType(nodeType string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNodeType", nodeType)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNodeType indicates an expected call of FindByNodeType.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindByNodeType(nodeType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNodeType", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindByNodeType), nodeType)
}

// FindEndNodes mocks base method.
func (m *MockApprovalNodeRepository) FindEndNodes(approvalDefCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEndNodes", approvalDefCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEndNodes indicates an expected call of FindEndNodes.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindEndNodes(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEndNodes", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindEndNodes), approvalDefCode)
}

// FindNextNodes mocks base method.
func (m *MockApprovalNodeRepository) FindNextNodes(approvalDefCode, currentNodeCode string) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNextNodes", approvalDefCode, currentNodeCode)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNextNodes indicates an expected call of FindNextNodes.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindNextNodes(approvalDefCode, currentNodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNextNodes", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindNextNodes), approvalDefCode, currentNodeCode)
}

// FindOne mocks base method.
func (m *MockApprovalNodeRepository) FindOne(id uint) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindOne(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindOne), id)
}

// FindPage mocks base method.
func (m *MockApprovalNodeRepository) FindPage(page, pageSize int, total *int64, where map[string]any) ([]*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindPage(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindPage), page, pageSize, total, where)
}

// FindStartNode mocks base method.
func (m *MockApprovalNodeRepository) FindStartNode(approvalDefCode string) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStartNode", approvalDefCode)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStartNode indicates an expected call of FindStartNode.
func (mr *MockApprovalNodeRepositoryMockRecorder) FindStartNode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStartNode", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FindStartNode), approvalDefCode)
}

// First mocks base method.
func (m *MockApprovalNodeRepository) First(where map[string]any) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalNodeRepositoryMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalNodeRepository)(nil).First), where)
}

// FirstByCode mocks base method.
func (m *MockApprovalNodeRepository) FirstByCode(code string) (*model.ApprovalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByCode", code)
	ret0, _ := ret[0].(*model.ApprovalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByCode indicates an expected call of FirstByCode.
func (mr *MockApprovalNodeRepositoryMockRecorder) FirstByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByCode", reflect.TypeOf((*MockApprovalNodeRepository)(nil).FirstByCode), code)
}

// Update mocks base method.
func (m *MockApprovalNodeRepository) Update(approvalNode *model.ApprovalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", approvalNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalNodeRepositoryMockRecorder) Update(approvalNode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalNodeRepository)(nil).Update), approvalNode)
}

// UpdateStatus mocks base method.
func (m *MockApprovalNodeRepository) UpdateStatus(id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockApprovalNodeRepositoryMockRecorder) UpdateStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockApprovalNodeRepository)(nil).UpdateStatus), id, status)
}

// UpdateStatusByIds mocks base method.
func (m *MockApprovalNodeRepository) UpdateStatusByIds(ids []uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByIds", ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByIds indicates an expected call of UpdateStatusByIds.
func (mr *MockApprovalNodeRepositoryMockRecorder) UpdateStatusByIds(ids, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByIds", reflect.TypeOf((*MockApprovalNodeRepository)(nil).UpdateStatusByIds), ids, status)
}
