// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/approval_definition.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockApprovalDefinitionRepository is a mock of ApprovalDefinitionRepository interface.
type MockApprovalDefinitionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalDefinitionRepositoryMockRecorder
}

// MockApprovalDefinitionRepositoryMockRecorder is the mock recorder for MockApprovalDefinitionRepository.
type MockApprovalDefinitionRepositoryMockRecorder struct {
	mock *MockApprovalDefinitionRepository
}

// NewMockApprovalDefinitionRepository creates a new mock instance.
func NewMockApprovalDefinitionRepository(ctrl *gomock.Controller) *MockApprovalDefinitionRepository {
	mock := &MockApprovalDefinitionRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalDefinitionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalDefinitionRepository) EXPECT() *MockApprovalDefinitionRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockApprovalDefinitionRepository) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockApprovalDefinitionRepository) BatchUpdate(c *gin.Context, ids []uint, approvalDefinition *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, approvalDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) BatchUpdate(c, ids, approvalDefinition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).BatchUpdate), c, ids, approvalDefinition)
}

// CountByEntityCode mocks base method.
func (m *MockApprovalDefinitionRepository) CountByEntityCode(entityCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByEntityCode", entityCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByEntityCode indicates an expected call of CountByEntityCode.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) CountByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByEntityCode", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).CountByEntityCode), entityCode)
}

// CountByStatus mocks base method.
func (m *MockApprovalDefinitionRepository) CountByStatus(status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) CountByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).CountByStatus), status)
}

// Create mocks base method.
func (m *MockApprovalDefinitionRepository) Create(c *gin.Context, approvalDefinition *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, approvalDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) Create(c, approvalDefinition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).Create), c, approvalDefinition)
}

// Delete mocks base method.
func (m *MockApprovalDefinitionRepository) Delete(c *gin.Context, id uint) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).Delete), c, id)
}

// FindActiveByEntityCode mocks base method.
func (m *MockApprovalDefinitionRepository) FindActiveByEntityCode(entityCode string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByEntityCode", entityCode)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByEntityCode indicates an expected call of FindActiveByEntityCode.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindActiveByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByEntityCode", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindActiveByEntityCode), entityCode)
}

// FindByCategory mocks base method.
func (m *MockApprovalDefinitionRepository) FindByCategory(category string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCategory", category)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCategory indicates an expected call of FindByCategory.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindByCategory(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCategory", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindByCategory), category)
}

// FindByEntityCode mocks base method.
func (m *MockApprovalDefinitionRepository) FindByEntityCode(entityCode string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEntityCode", entityCode)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEntityCode indicates an expected call of FindByEntityCode.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEntityCode", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindByEntityCode), entityCode)
}

// FindByStatus mocks base method.
func (m *MockApprovalDefinitionRepository) FindByStatus(status string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", status)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindByStatus), status)
}

// FindOne mocks base method.
func (m *MockApprovalDefinitionRepository) FindOne(id uint) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindOne(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindOne), id)
}

// FindPage mocks base method.
func (m *MockApprovalDefinitionRepository) FindPage(page, pageSize int, total *int64, where map[string]any) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindPage(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindPage), page, pageSize, total, where)
}

// FindVersionsByCode mocks base method.
func (m *MockApprovalDefinitionRepository) FindVersionsByCode(code string) ([]*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVersionsByCode", code)
	ret0, _ := ret[0].([]*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVersionsByCode indicates an expected call of FindVersionsByCode.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FindVersionsByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVersionsByCode", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FindVersionsByCode), code)
}

// First mocks base method.
func (m *MockApprovalDefinitionRepository) First(where map[string]any) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).First), where)
}

// FirstByCode mocks base method.
func (m *MockApprovalDefinitionRepository) FirstByCode(code string) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByCode", code)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByCode indicates an expected call of FirstByCode.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) FirstByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByCode", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).FirstByCode), code)
}

// GetLatestVersion mocks base method.
func (m *MockApprovalDefinitionRepository) GetLatestVersion(code string) (*model.ApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", code)
	ret0, _ := ret[0].(*model.ApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) GetLatestVersion(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).GetLatestVersion), code)
}

// Update mocks base method.
func (m *MockApprovalDefinitionRepository) Update(c *gin.Context, approvalDefinition *model.ApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, approvalDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) Update(c, approvalDefinition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).Update), c, approvalDefinition)
}

// UpdateStatus mocks base method.
func (m *MockApprovalDefinitionRepository) UpdateStatus(id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) UpdateStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).UpdateStatus), id, status)
}

// UpdateStatusByIds mocks base method.
func (m *MockApprovalDefinitionRepository) UpdateStatusByIds(ids []uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByIds", ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByIds indicates an expected call of UpdateStatusByIds.
func (mr *MockApprovalDefinitionRepositoryMockRecorder) UpdateStatusByIds(ids, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByIds", reflect.TypeOf((*MockApprovalDefinitionRepository)(nil).UpdateStatusByIds), ids, status)
}
