// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/approval.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"
	time "time"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockApprovalRepository is a mock of ApprovalRepository interface.
type MockApprovalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalRepositoryMockRecorder
}

// MockApprovalRepositoryMockRecorder is the mock recorder for MockApprovalRepository.
type MockApprovalRepositoryMockRecorder struct {
	mock *MockApprovalRepository
}

// NewMockApprovalRepository creates a new mock instance.
func NewMockApprovalRepository(ctrl *gomock.Controller) *MockApprovalRepository {
	mock := &MockApprovalRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalRepository) EXPECT() *MockApprovalRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockApprovalRepository) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalRepositoryMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalRepository)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockApprovalRepository) BatchUpdate(c *gin.Context, ids []uint, approval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, approval)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalRepositoryMockRecorder) BatchUpdate(c, ids, approval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalRepository)(nil).BatchUpdate), c, ids, approval)
}

// CountByApplicant mocks base method.
func (m *MockApprovalRepository) CountByApplicant(applicantID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByApplicant", applicantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByApplicant indicates an expected call of CountByApplicant.
func (mr *MockApprovalRepositoryMockRecorder) CountByApplicant(applicantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByApplicant", reflect.TypeOf((*MockApprovalRepository)(nil).CountByApplicant), applicantID)
}

// CountByApprovalDef mocks base method.
func (m *MockApprovalRepository) CountByApprovalDef(approvalDefCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByApprovalDef", approvalDefCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByApprovalDef indicates an expected call of CountByApprovalDef.
func (mr *MockApprovalRepositoryMockRecorder) CountByApprovalDef(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByApprovalDef", reflect.TypeOf((*MockApprovalRepository)(nil).CountByApprovalDef), approvalDefCode)
}

// CountByStatus mocks base method.
func (m *MockApprovalRepository) CountByStatus(status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockApprovalRepositoryMockRecorder) CountByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockApprovalRepository)(nil).CountByStatus), status)
}

// Create mocks base method.
func (m *MockApprovalRepository) Create(c *gin.Context, approval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, approval)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalRepositoryMockRecorder) Create(c, approval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalRepository)(nil).Create), c, approval)
}

// Delete mocks base method.
func (m *MockApprovalRepository) Delete(c *gin.Context, id uint) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalRepositoryMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalRepository)(nil).Delete), c, id)
}

// FindByApplicantID mocks base method.
func (m *MockApprovalRepository) FindByApplicantID(applicantID string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByApplicantID", applicantID)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByApplicantID indicates an expected call of FindByApplicantID.
func (mr *MockApprovalRepositoryMockRecorder) FindByApplicantID(applicantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByApplicantID", reflect.TypeOf((*MockApprovalRepository)(nil).FindByApplicantID), applicantID)
}

// FindByApprovalDefCode mocks base method.
func (m *MockApprovalRepository) FindByApprovalDefCode(approvalDefCode string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByApprovalDefCode", approvalDefCode)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByApprovalDefCode indicates an expected call of FindByApprovalDefCode.
func (mr *MockApprovalRepositoryMockRecorder) FindByApprovalDefCode(approvalDefCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByApprovalDefCode", reflect.TypeOf((*MockApprovalRepository)(nil).FindByApprovalDefCode), approvalDefCode)
}

// FindByEntityCode mocks base method.
func (m *MockApprovalRepository) FindByEntityCode(entityCode string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEntityCode", entityCode)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEntityCode indicates an expected call of FindByEntityCode.
func (mr *MockApprovalRepositoryMockRecorder) FindByEntityCode(entityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEntityCode", reflect.TypeOf((*MockApprovalRepository)(nil).FindByEntityCode), entityCode)
}

// FindByEntityID mocks base method.
func (m *MockApprovalRepository) FindByEntityID(entityCode, entityID string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEntityID", entityCode, entityID)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEntityID indicates an expected call of FindByEntityID.
func (mr *MockApprovalRepositoryMockRecorder) FindByEntityID(entityCode, entityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEntityID", reflect.TypeOf((*MockApprovalRepository)(nil).FindByEntityID), entityCode, entityID)
}

// FindByStatus mocks base method.
func (m *MockApprovalRepository) FindByStatus(status string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", status)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockApprovalRepositoryMockRecorder) FindByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockApprovalRepository)(nil).FindByStatus), status)
}

// FindExpiredApprovals mocks base method.
func (m *MockApprovalRepository) FindExpiredApprovals() ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiredApprovals")
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiredApprovals indicates an expected call of FindExpiredApprovals.
func (mr *MockApprovalRepositoryMockRecorder) FindExpiredApprovals() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiredApprovals", reflect.TypeOf((*MockApprovalRepository)(nil).FindExpiredApprovals))
}

// FindHistory mocks base method.
func (m *MockApprovalRepository) FindHistory(id uint) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHistory", id)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHistory indicates an expected call of FindHistory.
func (mr *MockApprovalRepositoryMockRecorder) FindHistory(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHistory", reflect.TypeOf((*MockApprovalRepository)(nil).FindHistory), id)
}

// FindOne mocks base method.
func (m *MockApprovalRepository) FindOne(id uint) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalRepositoryMockRecorder) FindOne(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalRepository)(nil).FindOne), id)
}

// FindPage mocks base method.
func (m *MockApprovalRepository) FindPage(page, pageSize int, total *int64, where map[string]any) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockApprovalRepositoryMockRecorder) FindPage(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockApprovalRepository)(nil).FindPage), page, pageSize, total, where)
}

// FindPendingByApplicant mocks base method.
func (m *MockApprovalRepository) FindPendingByApplicant(applicantID string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByApplicant", applicantID)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByApplicant indicates an expected call of FindPendingByApplicant.
func (mr *MockApprovalRepositoryMockRecorder) FindPendingByApplicant(applicantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByApplicant", reflect.TypeOf((*MockApprovalRepository)(nil).FindPendingByApplicant), applicantID)
}

// FindPendingByAssignee mocks base method.
func (m *MockApprovalRepository) FindPendingByAssignee(assigneeName string, page, pageSize int, total *int64, timeRange string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByAssignee", assigneeName, page, pageSize, total, timeRange)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByAssignee indicates an expected call of FindPendingByAssignee.
func (mr *MockApprovalRepositoryMockRecorder) FindPendingByAssignee(assigneeName, page, pageSize, total, timeRange interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByAssignee", reflect.TypeOf((*MockApprovalRepository)(nil).FindPendingByAssignee), assigneeName, page, pageSize, total, timeRange)
}

// FindProcessedByAssignee mocks base method.
func (m *MockApprovalRepository) FindProcessedByAssignee(assigneeName string, page, pageSize int, total *int64, timeRange string) ([]*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProcessedByAssignee", assigneeName, page, pageSize, total, timeRange)
	ret0, _ := ret[0].([]*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProcessedByAssignee indicates an expected call of FindProcessedByAssignee.
func (mr *MockApprovalRepositoryMockRecorder) FindProcessedByAssignee(assigneeName, page, pageSize, total, timeRange interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProcessedByAssignee", reflect.TypeOf((*MockApprovalRepository)(nil).FindProcessedByAssignee), assigneeName, page, pageSize, total, timeRange)
}

// First mocks base method.
func (m *MockApprovalRepository) First(where map[string]any) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalRepositoryMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalRepository)(nil).First), where)
}

// FirstByCode mocks base method.
func (m *MockApprovalRepository) FirstByCode(code string) (*model.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByCode", code)
	ret0, _ := ret[0].(*model.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByCode indicates an expected call of FirstByCode.
func (mr *MockApprovalRepositoryMockRecorder) FirstByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByCode", reflect.TypeOf((*MockApprovalRepository)(nil).FirstByCode), code)
}

// SaveToQueue mocks base method.
func (m *MockApprovalRepository) SaveToQueue(webhookReq model.WebhookReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToQueue", webhookReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToQueue indicates an expected call of SaveToQueue.
func (mr *MockApprovalRepositoryMockRecorder) SaveToQueue(webhookReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToQueue", reflect.TypeOf((*MockApprovalRepository)(nil).SaveToQueue), webhookReq)
}

// Update mocks base method.
func (m *MockApprovalRepository) Update(c *gin.Context, approval *model.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, approval)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalRepositoryMockRecorder) Update(c, approval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalRepository)(nil).Update), c, approval)
}

// UpdateCompletedAt mocks base method.
func (m *MockApprovalRepository) UpdateCompletedAt(c *gin.Context, id uint, completedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompletedAt", c, id, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCompletedAt indicates an expected call of UpdateCompletedAt.
func (mr *MockApprovalRepositoryMockRecorder) UpdateCompletedAt(c, id, completedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompletedAt", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateCompletedAt), c, id, completedAt)
}

// UpdateCurrentNode mocks base method.
func (m *MockApprovalRepository) UpdateCurrentNode(c *gin.Context, id uint, nodeID, nodeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentNode", c, id, nodeID, nodeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrentNode indicates an expected call of UpdateCurrentNode.
func (mr *MockApprovalRepositoryMockRecorder) UpdateCurrentNode(c, id, nodeID, nodeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrentNode", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateCurrentNode), c, id, nodeID, nodeName)
}

// UpdateExpiredAt mocks base method.
func (m *MockApprovalRepository) UpdateExpiredAt(c *gin.Context, id uint, expiredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpiredAt", c, id, expiredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExpiredAt indicates an expected call of UpdateExpiredAt.
func (mr *MockApprovalRepositoryMockRecorder) UpdateExpiredAt(c, id, expiredAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpiredAt", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateExpiredAt), c, id, expiredAt)
}

// UpdateStartedAt mocks base method.
func (m *MockApprovalRepository) UpdateStartedAt(c *gin.Context, id uint, startedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStartedAt", c, id, startedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStartedAt indicates an expected call of UpdateStartedAt.
func (mr *MockApprovalRepositoryMockRecorder) UpdateStartedAt(c, id, startedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStartedAt", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateStartedAt), c, id, startedAt)
}

// UpdateStatus mocks base method.
func (m *MockApprovalRepository) UpdateStatus(c *gin.Context, id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", c, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockApprovalRepositoryMockRecorder) UpdateStatus(c, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateStatus), c, id, status)
}

// UpdateStatusByCode mocks base method.
func (m *MockApprovalRepository) UpdateStatusByCode(c *gin.Context, code, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByCode", c, code, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByCode indicates an expected call of UpdateStatusByCode.
func (mr *MockApprovalRepositoryMockRecorder) UpdateStatusByCode(c, code, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByCode", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateStatusByCode), c, code, status)
}

// UpdateSubmittedAt mocks base method.
func (m *MockApprovalRepository) UpdateSubmittedAt(c *gin.Context, id uint, submittedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmittedAt", c, id, submittedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubmittedAt indicates an expected call of UpdateSubmittedAt.
func (mr *MockApprovalRepositoryMockRecorder) UpdateSubmittedAt(c, id, submittedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmittedAt", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateSubmittedAt), c, id, submittedAt)
}

// UpdateTaskCount mocks base method.
func (m *MockApprovalRepository) UpdateTaskCount(c *gin.Context, id uint, taskCount, completedTasks, pendingTasks int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskCount", c, id, taskCount, completedTasks, pendingTasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskCount indicates an expected call of UpdateTaskCount.
func (mr *MockApprovalRepositoryMockRecorder) UpdateTaskCount(c, id, taskCount, completedTasks, pendingTasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskCount", reflect.TypeOf((*MockApprovalRepository)(nil).UpdateTaskCount), c, id, taskCount, completedTasks, pendingTasks)
}
