// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/approval_task.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockApprovalTaskRepository is a mock of ApprovalTaskRepository interface.
type MockApprovalTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalTaskRepositoryMockRecorder
}

// MockApprovalTaskRepositoryMockRecorder is the mock recorder for MockApprovalTaskRepository.
type MockApprovalTaskRepositoryMockRecorder struct {
	mock *MockApprovalTaskRepository
}

// NewMockApprovalTaskRepository creates a new mock instance.
func NewMockApprovalTaskRepository(ctrl *gomock.Controller) *MockApprovalTaskRepository {
	mock := &MockApprovalTaskRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalTaskRepository) EXPECT() *MockApprovalTaskRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockApprovalTaskRepository) BatchDelete(ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockApprovalTaskRepositoryMockRecorder) BatchDelete(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockApprovalTaskRepository)(nil).BatchDelete), ids)
}

// BatchUpdate mocks base method.
func (m *MockApprovalTaskRepository) BatchUpdate(ids []uint, approvalTask *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ids, approvalTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockApprovalTaskRepositoryMockRecorder) BatchUpdate(ids, approvalTask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockApprovalTaskRepository)(nil).BatchUpdate), ids, approvalTask)
}

// BatchUpdateRemindInfo mocks base method.
func (m *MockApprovalTaskRepository) BatchUpdateRemindInfo(ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateRemindInfo", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateRemindInfo indicates an expected call of BatchUpdateRemindInfo.
func (mr *MockApprovalTaskRepositoryMockRecorder) BatchUpdateRemindInfo(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateRemindInfo", reflect.TypeOf((*MockApprovalTaskRepository)(nil).BatchUpdateRemindInfo), ids)
}

// CompleteTask mocks base method.
func (m *MockApprovalTaskRepository) CompleteTask(id uint, result, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTask", id, result, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTask indicates an expected call of CompleteTask.
func (mr *MockApprovalTaskRepositoryMockRecorder) CompleteTask(id, result, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTask", reflect.TypeOf((*MockApprovalTaskRepository)(nil).CompleteTask), id, result, comment, reason)
}

// CountByApprovalCode mocks base method.
func (m *MockApprovalTaskRepository) CountByApprovalCode(approvalCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByApprovalCode", approvalCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByApprovalCode indicates an expected call of CountByApprovalCode.
func (mr *MockApprovalTaskRepositoryMockRecorder) CountByApprovalCode(approvalCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByApprovalCode", reflect.TypeOf((*MockApprovalTaskRepository)(nil).CountByApprovalCode), approvalCode)
}

// CountByAssignee mocks base method.
func (m *MockApprovalTaskRepository) CountByAssignee(assigneeID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByAssignee", assigneeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByAssignee indicates an expected call of CountByAssignee.
func (mr *MockApprovalTaskRepositoryMockRecorder) CountByAssignee(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByAssignee", reflect.TypeOf((*MockApprovalTaskRepository)(nil).CountByAssignee), assigneeID)
}

// CountByNodeCode mocks base method.
func (m *MockApprovalTaskRepository) CountByNodeCode(nodeCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByNodeCode", nodeCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByNodeCode indicates an expected call of CountByNodeCode.
func (mr *MockApprovalTaskRepositoryMockRecorder) CountByNodeCode(nodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByNodeCode", reflect.TypeOf((*MockApprovalTaskRepository)(nil).CountByNodeCode), nodeCode)
}

// CountByStatus mocks base method.
func (m *MockApprovalTaskRepository) CountByStatus(status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockApprovalTaskRepositoryMockRecorder) CountByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockApprovalTaskRepository)(nil).CountByStatus), status)
}

// CountPendingByAssignee mocks base method.
func (m *MockApprovalTaskRepository) CountPendingByAssignee(assigneeID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByAssignee", assigneeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByAssignee indicates an expected call of CountPendingByAssignee.
func (mr *MockApprovalTaskRepositoryMockRecorder) CountPendingByAssignee(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByAssignee", reflect.TypeOf((*MockApprovalTaskRepository)(nil).CountPendingByAssignee), assigneeID)
}

// Create mocks base method.
func (m *MockApprovalTaskRepository) Create(approvalTask *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", approvalTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalTaskRepositoryMockRecorder) Create(approvalTask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalTaskRepository)(nil).Create), approvalTask)
}

// Delete mocks base method.
func (m *MockApprovalTaskRepository) Delete(id uint) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalTaskRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalTaskRepository)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockApprovalTaskRepository) Find(where map[string]any) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", where)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockApprovalTaskRepositoryMockRecorder) Find(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockApprovalTaskRepository)(nil).Find), where)
}

// FindByApprovalCode mocks base method.
func (m *MockApprovalTaskRepository) FindByApprovalCode(approvalCode string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByApprovalCode", approvalCode)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByApprovalCode indicates an expected call of FindByApprovalCode.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindByApprovalCode(approvalCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByApprovalCode", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindByApprovalCode), approvalCode)
}

// FindByAssigneeID mocks base method.
func (m *MockApprovalTaskRepository) FindByAssigneeID(assigneeID string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAssigneeID", assigneeID)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAssigneeID indicates an expected call of FindByAssigneeID.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindByAssigneeID(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAssigneeID", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindByAssigneeID), assigneeID)
}

// FindByNodeCode mocks base method.
func (m *MockApprovalTaskRepository) FindByNodeCode(nodeCode string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNodeCode", nodeCode)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNodeCode indicates an expected call of FindByNodeCode.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindByNodeCode(nodeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNodeCode", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindByNodeCode), nodeCode)
}

// FindByStatus mocks base method.
func (m *MockApprovalTaskRepository) FindByStatus(status string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", status)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindByStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindByStatus), status)
}

// FindExpiredTasks mocks base method.
func (m *MockApprovalTaskRepository) FindExpiredTasks() ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiredTasks")
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiredTasks indicates an expected call of FindExpiredTasks.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindExpiredTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiredTasks", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindExpiredTasks))
}

// FindOne mocks base method.
func (m *MockApprovalTaskRepository) FindOne(id uint) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindOne(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindOne), id)
}

// FindOverdueTasks mocks base method.
func (m *MockApprovalTaskRepository) FindOverdueTasks() ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdueTasks")
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdueTasks indicates an expected call of FindOverdueTasks.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindOverdueTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdueTasks", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindOverdueTasks))
}

// FindPage mocks base method.
func (m *MockApprovalTaskRepository) FindPage(page, pageSize int, total *int64, where map[string]any, order string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", page, pageSize, total, where, order)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindPage(page, pageSize, total, where, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindPage), page, pageSize, total, where, order)
}

// FindPendingByAssignee mocks base method.
func (m *MockApprovalTaskRepository) FindPendingByAssignee(assigneeID string) ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByAssignee", assigneeID)
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByAssignee indicates an expected call of FindPendingByAssignee.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindPendingByAssignee(assigneeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByAssignee", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindPendingByAssignee), assigneeID)
}

// FindTasksNeedRemind mocks base method.
func (m *MockApprovalTaskRepository) FindTasksNeedRemind() ([]*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTasksNeedRemind")
	ret0, _ := ret[0].([]*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTasksNeedRemind indicates an expected call of FindTasksNeedRemind.
func (mr *MockApprovalTaskRepositoryMockRecorder) FindTasksNeedRemind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTasksNeedRemind", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FindTasksNeedRemind))
}

// First mocks base method.
func (m *MockApprovalTaskRepository) First(where map[string]any) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", where)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApprovalTaskRepositoryMockRecorder) First(where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockApprovalTaskRepository)(nil).First), where)
}

// FirstByCode mocks base method.
func (m *MockApprovalTaskRepository) FirstByCode(code string) (*model.ApprovalTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByCode", code)
	ret0, _ := ret[0].(*model.ApprovalTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByCode indicates an expected call of FirstByCode.
func (mr *MockApprovalTaskRepositoryMockRecorder) FirstByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByCode", reflect.TypeOf((*MockApprovalTaskRepository)(nil).FirstByCode), code)
}

// TransferTask mocks base method.
func (m *MockApprovalTaskRepository) TransferTask(id uint, fromUserID, toUserID, fromUserName, toUserName, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTask", id, fromUserID, toUserID, fromUserName, toUserName, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferTask indicates an expected call of TransferTask.
func (mr *MockApprovalTaskRepositoryMockRecorder) TransferTask(id, fromUserID, toUserID, fromUserName, toUserName, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTask", reflect.TypeOf((*MockApprovalTaskRepository)(nil).TransferTask), id, fromUserID, toUserID, fromUserName, toUserName, reason)
}

// Update mocks base method.
func (m *MockApprovalTaskRepository) Update(approvalTask *model.ApprovalTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", approvalTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalTaskRepositoryMockRecorder) Update(approvalTask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalTaskRepository)(nil).Update), approvalTask)
}

// UpdateAssignedAt mocks base method.
func (m *MockApprovalTaskRepository) UpdateAssignedAt(id uint, assignedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssignedAt", id, assignedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAssignedAt indicates an expected call of UpdateAssignedAt.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateAssignedAt(id, assignedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssignedAt", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateAssignedAt), id, assignedAt)
}

// UpdateCompletedAt mocks base method.
func (m *MockApprovalTaskRepository) UpdateCompletedAt(id uint, completedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompletedAt", id, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCompletedAt indicates an expected call of UpdateCompletedAt.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateCompletedAt(id, completedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompletedAt", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateCompletedAt), id, completedAt)
}

// UpdateExpiredAt mocks base method.
func (m *MockApprovalTaskRepository) UpdateExpiredAt(id uint, expiredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpiredAt", id, expiredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExpiredAt indicates an expected call of UpdateExpiredAt.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateExpiredAt(id, expiredAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpiredAt", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateExpiredAt), id, expiredAt)
}

// UpdateLastRemindAt mocks base method.
func (m *MockApprovalTaskRepository) UpdateLastRemindAt(id uint, lastRemindAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastRemindAt", id, lastRemindAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastRemindAt indicates an expected call of UpdateLastRemindAt.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateLastRemindAt(id, lastRemindAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastRemindAt", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateLastRemindAt), id, lastRemindAt)
}

// UpdateRemindCount mocks base method.
func (m *MockApprovalTaskRepository) UpdateRemindCount(id uint, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRemindCount", id, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRemindCount indicates an expected call of UpdateRemindCount.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateRemindCount(id, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRemindCount", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateRemindCount), id, count)
}

// UpdateRemindInfo mocks base method.
func (m *MockApprovalTaskRepository) UpdateRemindInfo(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRemindInfo", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRemindInfo indicates an expected call of UpdateRemindInfo.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateRemindInfo(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRemindInfo", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateRemindInfo), id)
}

// UpdateResult mocks base method.
func (m *MockApprovalTaskRepository) UpdateResult(id uint, result, comment, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResult", id, result, comment, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResult indicates an expected call of UpdateResult.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateResult(id, result, comment, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResult", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateResult), id, result, comment, reason)
}

// UpdateStartedAt mocks base method.
func (m *MockApprovalTaskRepository) UpdateStartedAt(id uint, startedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStartedAt", id, startedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStartedAt indicates an expected call of UpdateStartedAt.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateStartedAt(id, startedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStartedAt", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateStartedAt), id, startedAt)
}

// UpdateStatus mocks base method.
func (m *MockApprovalTaskRepository) UpdateStatus(id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockApprovalTaskRepositoryMockRecorder) UpdateStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockApprovalTaskRepository)(nil).UpdateStatus), id, status)
}
