// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/entity.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockEntityRepository is a mock of EntityRepository interface.
type MockEntityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntityRepositoryMockRecorder
}

// MockEntityRepositoryMockRecorder is the mock recorder for MockEntityRepository.
type MockEntityRepositoryMockRecorder struct {
	mock *MockEntityRepository
}

// NewMockEntityRepository creates a new mock instance.
func NewMockEntityRepository(ctrl *gomock.Controller) *MockEntityRepository {
	mock := &MockEntityRepository{ctrl: ctrl}
	mock.recorder = &MockEntityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityRepository) EXPECT() *MockEntityRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockEntityRepository) BatchDelete(c *gin.Context, tableCode string, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, tableCode, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockEntityRepositoryMockRecorder) BatchDelete(c, tableCode, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockEntityRepository)(nil).BatchDelete), c, tableCode, ids)
}

// BatchUpdate mocks base method.
func (m *MockEntityRepository) BatchUpdate(c *gin.Context, tableCode string, ids []uint, entityMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, tableCode, ids, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockEntityRepositoryMockRecorder) BatchUpdate(c, tableCode, ids, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockEntityRepository)(nil).BatchUpdate), c, tableCode, ids, entityMap)
}

// Create mocks base method.
func (m *MockEntityRepository) Create(c *gin.Context, tableCode string, entityMap any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, tableCode, entityMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEntityRepositoryMockRecorder) Create(c, tableCode, entityMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntityRepository)(nil).Create), c, tableCode, entityMap)
}

// Delete mocks base method.
func (m *MockEntityRepository) Delete(c *gin.Context, tableCode string, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, tableCode, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEntityRepositoryMockRecorder) Delete(c, tableCode, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEntityRepository)(nil).Delete), c, tableCode, id)
}

// Find mocks base method.
func (m *MockEntityRepository) Find(tableCode, selectString string, where map[string]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", tableCode, selectString, where)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockEntityRepositoryMockRecorder) Find(tableCode, selectString, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockEntityRepository)(nil).Find), tableCode, selectString, where)
}

// FindLogPage mocks base method.
func (m *MockEntityRepository) FindLogPage(tableCode string, page, pageSize int, total *int64, where map[string]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLogPage", tableCode, page, pageSize, total, where)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLogPage indicates an expected call of FindLogPage.
func (mr *MockEntityRepositoryMockRecorder) FindLogPage(tableCode, page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLogPage", reflect.TypeOf((*MockEntityRepository)(nil).FindLogPage), tableCode, page, pageSize, total, where)
}

// FindOne mocks base method.
func (m *MockEntityRepository) FindOne(tableCode string, id uint) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", tableCode, id)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockEntityRepositoryMockRecorder) FindOne(tableCode, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockEntityRepository)(nil).FindOne), tableCode, id)
}

// FindPage mocks base method.
func (m *MockEntityRepository) FindPage(tableCode string, page, pageSize int, total *int64, where map[string]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", tableCode, page, pageSize, total, where)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockEntityRepositoryMockRecorder) FindPage(tableCode, page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockEntityRepository)(nil).FindPage), tableCode, page, pageSize, total, where)
}

// GetStatisticsByStatus mocks base method.
func (m *MockEntityRepository) GetStatisticsByStatus(tableCode string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticsByStatus", tableCode)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticsByStatus indicates an expected call of GetStatisticsByStatus.
func (mr *MockEntityRepositoryMockRecorder) GetStatisticsByStatus(tableCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticsByStatus", reflect.TypeOf((*MockEntityRepository)(nil).GetStatisticsByStatus), tableCode)
}

// Update mocks base method.
func (m *MockEntityRepository) Update(c *gin.Context, tableCode string, entity any, where map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, tableCode, entity, where)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEntityRepositoryMockRecorder) Update(c, tableCode, entity, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEntityRepository)(nil).Update), c, tableCode, entity, where)
}
