// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/notification_template.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "piemdm/internal/model"
	repository "piemdm/internal/repository"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationTemplateRepository is a mock of NotificationTemplateRepository interface.
type MockNotificationTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationTemplateRepositoryMockRecorder
}

// MockNotificationTemplateRepositoryMockRecorder is the mock recorder for MockNotificationTemplateRepository.
type MockNotificationTemplateRepositoryMockRecorder struct {
	mock *MockNotificationTemplateRepository
}

// NewMockNotificationTemplateRepository creates a new mock instance.
func NewMockNotificationTemplateRepository(ctrl *gomock.Controller) *MockNotificationTemplateRepository {
	mock := &MockNotificationTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationTemplateRepository) EXPECT() *MockNotificationTemplateRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockNotificationTemplateRepository) Count(ctx context.Context, req *repository.ListNotificationTemplateRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Count(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Count), ctx, req)
}

// Create mocks base method.
func (m *MockNotificationTemplateRepository) Create(ctx context.Context, template *model.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Create(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Create), ctx, template)
}

// Delete mocks base method.
func (m *MockNotificationTemplateRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Delete), ctx, id)
}

// FindOne mocks base method.
func (m *MockNotificationTemplateRepository) FindOne(ctx context.Context, id string) (*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockNotificationTemplateRepositoryMockRecorder) FindOne(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).FindOne), ctx, id)
}

// FindPage mocks base method.
func (m *MockNotificationTemplateRepository) FindPage(ctx context.Context, req *repository.ListNotificationTemplateRequest) ([]*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, req)
	ret0, _ := ret[0].([]*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockNotificationTemplateRepositoryMockRecorder) FindPage(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).FindPage), ctx, req)
}

// FirstByCode mocks base method.
func (m *MockNotificationTemplateRepository) FirstByCode(ctx context.Context, templateCode string) (*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByCode", ctx, templateCode)
	ret0, _ := ret[0].(*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByCode indicates an expected call of FirstByCode.
func (mr *MockNotificationTemplateRepositoryMockRecorder) FirstByCode(ctx, templateCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByCode", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).FirstByCode), ctx, templateCode)
}

// GetActiveTemplates mocks base method.
func (m *MockNotificationTemplateRepository) GetActiveTemplates(ctx context.Context, templateType string) ([]*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTemplates", ctx, templateType)
	ret0, _ := ret[0].([]*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTemplates indicates an expected call of GetActiveTemplates.
func (mr *MockNotificationTemplateRepositoryMockRecorder) GetActiveTemplates(ctx, templateType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTemplates", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).GetActiveTemplates), ctx, templateType)
}

// GetByTypeAndNotification mocks base method.
func (m *MockNotificationTemplateRepository) GetByTypeAndNotification(ctx context.Context, templateType, notificationType string) (*model.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTypeAndNotification", ctx, templateType, notificationType)
	ret0, _ := ret[0].(*model.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTypeAndNotification indicates an expected call of GetByTypeAndNotification.
func (mr *MockNotificationTemplateRepositoryMockRecorder) GetByTypeAndNotification(ctx, templateType, notificationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTypeAndNotification", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).GetByTypeAndNotification), ctx, templateType, notificationType)
}

// Update mocks base method.
func (m *MockNotificationTemplateRepository) Update(ctx context.Context, template *model.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Update(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Update), ctx, template)
}

// UpdateStatus mocks base method.
func (m *MockNotificationTemplateRepository) UpdateStatus(ctx context.Context, ids []string, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationTemplateRepositoryMockRecorder) UpdateStatus(ctx, ids, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).UpdateStatus), ctx, ids, status)
}
