// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/notification_log.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "piemdm/internal/model"
	repository "piemdm/internal/repository"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationLogRepository is a mock of NotificationLogRepository interface.
type MockNotificationLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationLogRepositoryMockRecorder
}

// MockNotificationLogRepositoryMockRecorder is the mock recorder for MockNotificationLogRepository.
type MockNotificationLogRepositoryMockRecorder struct {
	mock *MockNotificationLogRepository
}

// NewMockNotificationLogRepository creates a new mock instance.
func NewMockNotificationLogRepository(ctrl *gomock.Controller) *MockNotificationLogRepository {
	mock := &MockNotificationLogRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationLogRepository) EXPECT() *MockNotificationLogRepositoryMockRecorder {
	return m.recorder
}

// BatchUpdateStatus mocks base method.
func (m *MockNotificationLogRepository) BatchUpdateStatus(ctx context.Context, ids []uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateStatus", ctx, ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateStatus indicates an expected call of BatchUpdateStatus.
func (mr *MockNotificationLogRepositoryMockRecorder) BatchUpdateStatus(ctx, ids, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateStatus", reflect.TypeOf((*MockNotificationLogRepository)(nil).BatchUpdateStatus), ctx, ids, status)
}

// Count mocks base method.
func (m *MockNotificationLogRepository) Count(ctx context.Context, req *repository.ListNotificationLogRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockNotificationLogRepositoryMockRecorder) Count(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockNotificationLogRepository)(nil).Count), ctx, req)
}

// Create mocks base method.
func (m *MockNotificationLogRepository) Create(ctx context.Context, log *model.NotificationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationLogRepositoryMockRecorder) Create(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationLogRepository)(nil).Create), ctx, log)
}

// DeleteExpiredLogs mocks base method.
func (m *MockNotificationLogRepository) DeleteExpiredLogs(ctx context.Context, expiredBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredLogs", ctx, expiredBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredLogs indicates an expected call of DeleteExpiredLogs.
func (mr *MockNotificationLogRepositoryMockRecorder) DeleteExpiredLogs(ctx, expiredBefore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredLogs", reflect.TypeOf((*MockNotificationLogRepository)(nil).DeleteExpiredLogs), ctx, expiredBefore)
}

// FindOne mocks base method.
func (m *MockNotificationLogRepository) FindOne(ctx context.Context, id uint) (*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockNotificationLogRepositoryMockRecorder) FindOne(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockNotificationLogRepository)(nil).FindOne), ctx, id)
}

// FindPage mocks base method.
func (m *MockNotificationLogRepository) FindPage(ctx context.Context, req *repository.ListNotificationLogRequest) ([]*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, req)
	ret0, _ := ret[0].([]*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockNotificationLogRepositoryMockRecorder) FindPage(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockNotificationLogRepository)(nil).FindPage), ctx, req)
}

// GetByApprovalID mocks base method.
func (m *MockNotificationLogRepository) GetByApprovalID(ctx context.Context, approvalID string) ([]*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByApprovalID", ctx, approvalID)
	ret0, _ := ret[0].([]*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByApprovalID indicates an expected call of GetByApprovalID.
func (mr *MockNotificationLogRepositoryMockRecorder) GetByApprovalID(ctx, approvalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByApprovalID", reflect.TypeOf((*MockNotificationLogRepository)(nil).GetByApprovalID), ctx, approvalID)
}

// GetByRecipient mocks base method.
func (m *MockNotificationLogRepository) GetByRecipient(ctx context.Context, recipientID, recipientType string, limit int) ([]*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRecipient", ctx, recipientID, recipientType, limit)
	ret0, _ := ret[0].([]*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRecipient indicates an expected call of GetByRecipient.
func (mr *MockNotificationLogRepositoryMockRecorder) GetByRecipient(ctx, recipientID, recipientType, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRecipient", reflect.TypeOf((*MockNotificationLogRepository)(nil).GetByRecipient), ctx, recipientID, recipientType, limit)
}

// GetByTaskID mocks base method.
func (m *MockNotificationLogRepository) GetByTaskID(ctx context.Context, taskID string) ([]*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTaskID indicates an expected call of GetByTaskID.
func (mr *MockNotificationLogRepositoryMockRecorder) GetByTaskID(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTaskID", reflect.TypeOf((*MockNotificationLogRepository)(nil).GetByTaskID), ctx, taskID)
}

// GetPendingLogs mocks base method.
func (m *MockNotificationLogRepository) GetPendingLogs(ctx context.Context, limit int) ([]*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingLogs", ctx, limit)
	ret0, _ := ret[0].([]*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingLogs indicates an expected call of GetPendingLogs.
func (mr *MockNotificationLogRepositoryMockRecorder) GetPendingLogs(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingLogs", reflect.TypeOf((*MockNotificationLogRepository)(nil).GetPendingLogs), ctx, limit)
}

// GetRetryLogs mocks base method.
func (m *MockNotificationLogRepository) GetRetryLogs(ctx context.Context, limit int) ([]*model.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryLogs", ctx, limit)
	ret0, _ := ret[0].([]*model.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetryLogs indicates an expected call of GetRetryLogs.
func (mr *MockNotificationLogRepositoryMockRecorder) GetRetryLogs(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryLogs", reflect.TypeOf((*MockNotificationLogRepository)(nil).GetRetryLogs), ctx, limit)
}

// GetStatistics mocks base method.
func (m *MockNotificationLogRepository) GetStatistics(ctx context.Context, req *repository.NotificationStatisticsRequest) (*repository.NotificationStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx, req)
	ret0, _ := ret[0].(*repository.NotificationStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockNotificationLogRepositoryMockRecorder) GetStatistics(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockNotificationLogRepository)(nil).GetStatistics), ctx, req)
}

// Update mocks base method.
func (m *MockNotificationLogRepository) Update(ctx context.Context, log *model.NotificationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationLogRepositoryMockRecorder) Update(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationLogRepository)(nil).Update), ctx, log)
}
