// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/table.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockTableRepository is a mock of TableRepository interface.
type MockTableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTableRepositoryMockRecorder
}

// MockTableRepositoryMockRecorder is the mock recorder for MockTableRepository.
type MockTableRepositoryMockRecorder struct {
	mock *MockTableRepository
}

// NewMockTableRepository creates a new mock instance.
func NewMockTableRepository(ctrl *gomock.Controller) *MockTableRepository {
	mock := &MockTableRepository{ctrl: ctrl}
	mock.recorder = &MockTableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableRepository) EXPECT() *MockTableRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockTableRepository) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockTableRepositoryMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockTableRepository)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockTableRepository) BatchUpdate(c *gin.Context, ids []uint, table *model.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockTableRepositoryMockRecorder) BatchUpdate(c, ids, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockTableRepository)(nil).BatchUpdate), c, ids, table)
}

// Create mocks base method.
func (m *MockTableRepository) Create(c *gin.Context, table *model.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTableRepositoryMockRecorder) Create(c, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTableRepository)(nil).Create), c, table)
}

// Delete mocks base method.
func (m *MockTableRepository) Delete(c *gin.Context, id uint) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTableRepositoryMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTableRepository)(nil).Delete), c, id)
}

// Find mocks base method.
func (m *MockTableRepository) Find(sel string, where map[string]any) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", sel, where)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTableRepositoryMockRecorder) Find(sel, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTableRepository)(nil).Find), sel, where)
}

// FindOne mocks base method.
func (m *MockTableRepository) FindOne(id uint) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockTableRepositoryMockRecorder) FindOne(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockTableRepository)(nil).FindOne), id)
}

// FindPage mocks base method.
func (m *MockTableRepository) FindPage(page, pageSize int, total *int64, where map[string]any) ([]*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockTableRepositoryMockRecorder) FindPage(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockTableRepository)(nil).FindPage), page, pageSize, total, where)
}

// First mocks base method.
func (m *MockTableRepository) First(sel string, tableField model.Table) (*model.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", sel, tableField)
	ret0, _ := ret[0].(*model.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockTableRepositoryMockRecorder) First(sel, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockTableRepository)(nil).First), sel, tableField)
}

// Update mocks base method.
func (m *MockTableRepository) Update(c *gin.Context, table *model.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTableRepositoryMockRecorder) Update(c, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTableRepository)(nil).Update), c, table)
}
