// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/table_approval_definition.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockTableApprovalDefinitionRepository is a mock of TableApprovalDefinitionRepository interface.
type MockTableApprovalDefinitionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTableApprovalDefinitionRepositoryMockRecorder
}

// MockTableApprovalDefinitionRepositoryMockRecorder is the mock recorder for MockTableApprovalDefinitionRepository.
type MockTableApprovalDefinitionRepositoryMockRecorder struct {
	mock *MockTableApprovalDefinitionRepository
}

// NewMockTableApprovalDefinitionRepository creates a new mock instance.
func NewMockTableApprovalDefinitionRepository(ctrl *gomock.Controller) *MockTableApprovalDefinitionRepository {
	mock := &MockTableApprovalDefinitionRepository{ctrl: ctrl}
	mock.recorder = &MockTableApprovalDefinitionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableApprovalDefinitionRepository) EXPECT() *MockTableApprovalDefinitionRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockTableApprovalDefinitionRepository) BatchCreate(c *gin.Context, list []model.TableApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", c, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) BatchCreate(c, list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).BatchCreate), c, list)
}

// BatchDelete mocks base method.
func (m *MockTableApprovalDefinitionRepository) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).BatchDelete), c, ids)
}

// Create mocks base method.
func (m *MockTableApprovalDefinitionRepository) Create(c *gin.Context, item *model.TableApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) Create(c, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).Create), c, item)
}

// Delete mocks base method.
func (m *MockTableApprovalDefinitionRepository) Delete(c *gin.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).Delete), c, id)
}

// Get mocks base method.
func (m *MockTableApprovalDefinitionRepository) Get(id uint) (*model.TableApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.TableApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).Get), id)
}

// List mocks base method.
func (m *MockTableApprovalDefinitionRepository) List(entityCode, operation string) ([]model.TableApprovalDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", entityCode, operation)
	ret0, _ := ret[0].([]model.TableApprovalDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) List(entityCode, operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).List), entityCode, operation)
}

// Update mocks base method.
func (m *MockTableApprovalDefinitionRepository) Update(c *gin.Context, item *model.TableApprovalDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTableApprovalDefinitionRepositoryMockRecorder) Update(c, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTableApprovalDefinitionRepository)(nil).Update), c, item)
}
