// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/table_field.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockTableFieldRepository is a mock of TableFieldRepository interface.
type MockTableFieldRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTableFieldRepositoryMockRecorder
}

// MockTableFieldRepositoryMockRecorder is the mock recorder for MockTableFieldRepository.
type MockTableFieldRepositoryMockRecorder struct {
	mock *MockTableFieldRepository
}

// NewMockTableFieldRepository creates a new mock instance.
func NewMockTableFieldRepository(ctrl *gomock.Controller) *MockTableFieldRepository {
	mock := &MockTableFieldRepository{ctrl: ctrl}
	mock.recorder = &MockTableFieldRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableFieldRepository) EXPECT() *MockTableFieldRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockTableFieldRepository) BatchDelete(c *gin.Context, ids []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", c, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockTableFieldRepositoryMockRecorder) BatchDelete(c, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockTableFieldRepository)(nil).BatchDelete), c, ids)
}

// BatchUpdate mocks base method.
func (m *MockTableFieldRepository) BatchUpdate(c *gin.Context, ids []uint, tableField *model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", c, ids, tableField)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockTableFieldRepositoryMockRecorder) BatchUpdate(c, ids, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockTableFieldRepository)(nil).BatchUpdate), c, ids, tableField)
}

// BuildEntity mocks base method.
func (m *MockTableFieldRepository) BuildEntity(tableCode string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildEntity", tableCode)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// BuildEntity indicates an expected call of BuildEntity.
func (mr *MockTableFieldRepositoryMockRecorder) BuildEntity(tableCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildEntity", reflect.TypeOf((*MockTableFieldRepository)(nil).BuildEntity), tableCode)
}

// Create mocks base method.
func (m *MockTableFieldRepository) Create(c *gin.Context, tableField *model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, tableField)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTableFieldRepositoryMockRecorder) Create(c, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTableFieldRepository)(nil).Create), c, tableField)
}

// Delete mocks base method.
func (m *MockTableFieldRepository) Delete(c *gin.Context, id uint) (*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTableFieldRepositoryMockRecorder) Delete(c, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTableFieldRepository)(nil).Delete), c, id)
}

// Find mocks base method.
func (m *MockTableFieldRepository) Find(sel string, where map[string]any) ([]*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", sel, where)
	ret0, _ := ret[0].([]*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTableFieldRepositoryMockRecorder) Find(sel, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTableFieldRepository)(nil).Find), sel, where)
}

// FindOne mocks base method.
func (m *MockTableFieldRepository) FindOne(id uint) (*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockTableFieldRepositoryMockRecorder) FindOne(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockTableFieldRepository)(nil).FindOne), id)
}

// FindPage mocks base method.
func (m *MockTableFieldRepository) FindPage(page, pageSize int, total *int64, where map[string]any) ([]*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", page, pageSize, total, where)
	ret0, _ := ret[0].([]*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPage indicates an expected call of FindPage.
func (mr *MockTableFieldRepositoryMockRecorder) FindPage(page, pageSize, total, where interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockTableFieldRepository)(nil).FindPage), page, pageSize, total, where)
}

// First mocks base method.
func (m *MockTableFieldRepository) First(sel string, tableField model.TableField) (*model.TableField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", sel, tableField)
	ret0, _ := ret[0].(*model.TableField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockTableFieldRepositoryMockRecorder) First(sel, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockTableFieldRepository)(nil).First), sel, tableField)
}

// GetTableOptions mocks base method.
func (m *MockTableFieldRepository) GetTableOptions(tableCode string, filter map[string]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableOptions", tableCode, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableOptions indicates an expected call of GetTableOptions.
func (mr *MockTableFieldRepositoryMockRecorder) GetTableOptions(tableCode, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableOptions", reflect.TypeOf((*MockTableFieldRepository)(nil).GetTableOptions), tableCode, filter)
}

// Public mocks base method.
func (m *MockTableFieldRepository) Public(tableName string, entity any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Public", tableName, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Public indicates an expected call of Public.
func (mr *MockTableFieldRepositoryMockRecorder) Public(tableName, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Public", reflect.TypeOf((*MockTableFieldRepository)(nil).Public), tableName, entity)
}

// Update mocks base method.
func (m *MockTableFieldRepository) Update(c *gin.Context, tableField *model.TableField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, tableField)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTableFieldRepositoryMockRecorder) Update(c, tableField interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTableFieldRepository)(nil).Update), c, tableField)
}
