// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user_role.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "piemdm/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRoleRepository is a mock of UserRoleRepository interface.
type MockUserRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleRepositoryMockRecorder
}

// MockUserRoleRepositoryMockRecorder is the mock recorder for MockUserRoleRepository.
type MockUserRoleRepositoryMockRecorder struct {
	mock *MockUserRoleRepository
}

// NewMockUserRoleRepository creates a new mock instance.
func NewMockUserRoleRepository(ctrl *gomock.Controller) *MockUserRoleRepository {
	mock := &MockUserRoleRepository{ctrl: ctrl}
	mock.recorder = &MockUserRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleRepository) EXPECT() *MockUserRoleRepositoryMockRecorder {
	return m.recorder
}

// FindRolesByUserID mocks base method.
func (m *MockUserRoleRepository) FindRolesByUserID(userID uint) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByUserID", userID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByUserID indicates an expected call of FindRolesByUserID.
func (mr *MockUserRoleRepositoryMockRecorder) FindRolesByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByUserID", reflect.TypeOf((*MockUserRoleRepository)(nil).FindRolesByUserID), userID)
}

// FindUsersByRoleID mocks base method.
func (m *MockUserRoleRepository) FindUsersByRoleID(roleID uint) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByRoleID", roleID)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByRoleID indicates an expected call of FindUsersByRoleID.
func (mr *MockUserRoleRepositoryMockRecorder) FindUsersByRoleID(roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByRoleID", reflect.TypeOf((*MockUserRoleRepository)(nil).FindUsersByRoleID), roleID)
}

// UpdateRoleUsers mocks base method.
func (m *MockUserRoleRepository) UpdateRoleUsers(roleID uint, userIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoleUsers", roleID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoleUsers indicates an expected call of UpdateRoleUsers.
func (mr *MockUserRoleRepositoryMockRecorder) UpdateRoleUsers(roleID, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoleUsers", reflect.TypeOf((*MockUserRoleRepository)(nil).UpdateRoleUsers), roleID, userIDs)
}

// UpdateUserRoles mocks base method.
func (m *MockUserRoleRepository) UpdateUserRoles(userID uint, roleIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoles", userID, roleIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRoles indicates an expected call of UpdateUserRoles.
func (mr *MockUserRoleRepositoryMockRecorder) UpdateUserRoles(userID, roleIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoles", reflect.TypeOf((*MockUserRoleRepository)(nil).UpdateUserRoles), userID, roleIDs)
}
