// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"piemdm/internal/repository"
	"piemdm/internal/service"
	"piemdm/pkg/cron/job"
	"piemdm/pkg/helper/sid"
	"piemdm/pkg/jwt"
	"piemdm/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*job.Scanner, func(), error) {
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJwt(viperViper)
	client := repository.NewRedis(viperViper)
	db := repository.NewDB(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	base := repository.NewBaseRepository(repositoryRepository)
	userRepository := repository.NewUserRepository(repositoryRepository, base)
	userRoleRepository := repository.NewUserRoleRepository(db)
	userService := service.NewUserService(logger, sidSid, jwtJWT, client, userRepository, userRoleRepository)
	serviceService := service.NewService(logger, sidSid, jwtJWT)
	cronRepository := repository.NewCronRepository(repositoryRepository, base)
	cronService := service.NewCronService(serviceService, cronRepository)
	scanner := job.NewScanner(userService, cronService)
	return scanner, func() {
	}, nil
}

// wire.go:

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewCronService)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewBaseRepository, repository.NewUserRepository, repository.NewUserRoleRepository, repository.NewCronRepository)

var JobSet = wire.NewSet(job.NewScanner)
