// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"piemdm/internal/repository"
	"piemdm/pkg/helper/sid"
	"piemdm/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*Migrate, func(), error) {
	db := repository.NewDB(viperViper)
	sidSid := sid.NewSid()
	migrate := NewMigrate(db, logger, sidSid)
	return migrate, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewBaseRepository, repository.NewUserRepository)
