/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InternalHandlerUpdatePermissionRequest
 */
export interface InternalHandlerUpdatePermissionRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'parent_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof InternalHandlerUpdatePermissionRequest
     */
    'resource'?: string;
}

