/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelNotificationLog
 */
export interface PiemdmInternalModelNotificationLog {
    /**
     * 审批实例ID
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'ApprovalID'?: string;
    /**
     * 通知内容
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'Content': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'CreatedAt'?: string;
    /**
     * 错误信息
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'ErrorMessage'?: string;
    /**
     * 额外数据JSON
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'ExtraData'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'ID'?: number;
    /**
     * 最大重试次数
     * @type {number}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'MaxRetryCount'?: number;
    /**
     * 下次重试时间
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'NextRetryTime'?: string;
    /**
     * 通知类型
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'NotificationType': string;
    /**
     * 接收人ID
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'RecipientID': string;
    /**
     * 接收人类型
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'RecipientType': string;
    /**
     * 重试次数
     * @type {number}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'RetryCount'?: number;
    /**
     * 发送时间
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'SendTime'?: string;
    /**
     * 发送状态
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'Status'?: string;
    /**
     * 任务ID
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'TaskID'?: string;
    /**
     * 模板编码
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'TemplateCode'?: string;
    /**
     * 模板ID
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'TemplateID'?: string;
    /**
     * 通知标题
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'Title': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelNotificationLog
     */
    'UpdatedAt'?: string;
}

