/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelApprovalNode
 */
export interface PiemdmInternalModelApprovalNode {
    /**
     * 审批定义编码
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'approvalDefCode': string;
    /**
     * 审批人配置JSON
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'approverConfig'?: string;
    /**
     * 审批配置
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'approverType'?: string;
    /**
     * 条件配置JSON
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'conditionConfig'?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'createdAt'?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 节点描述，审批要点
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'id'?: number;
    /**
     * 节点编码
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'nodeCode'?: string;
    /**
     * 节点名称
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'nodeName'?: string;
    /**
     * 节点类型：START/APPROVAL/CONDITION/CC/END/PARALLEL/MERGE
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'nodeType'?: string;
    /**
     * 排序
     * @type {number}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'sortOrder'?: number;
    /**
     * 状态:Normal 正常, Frozen 已冻结, Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'status'?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelApprovalNode
     */
    'updatedBy'?: string;
}

