/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelPermission } from './piemdm-internal-model-permission';

/**
 * 
 * @export
 * @interface PiemdmInternalModelRole
 */
export interface PiemdmInternalModelRole {
    /**
     * 表名,英文
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'createdAt'?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'createdBy'?: string;
    /**
     * 数据范围: All, Subordinate, Self
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'data_scope'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelRole
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 描述
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'desc'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelRole
     */
    'id'?: number;
    /**
     * 名称，可以中文
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'name': string;
    /**
     * 
     * @type {Array<PiemdmInternalModelPermission>}
     * @memberof PiemdmInternalModelRole
     */
    'permissions'?: Array<PiemdmInternalModelPermission>;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelRole
     */
    'updatedBy'?: string;
}

