/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalServiceTestNotificationRequest
 */
export interface PiemdmInternalServiceTestNotificationRequest {
    /**
     * 内容
     * @type {string}
     * @memberof PiemdmInternalServiceTestNotificationRequest
     */
    'content'?: string;
    /**
     * 通知类型
     * @type {string}
     * @memberof PiemdmInternalServiceTestNotificationRequest
     */
    'notification_type'?: string;
    /**
     * 接收人ID
     * @type {string}
     * @memberof PiemdmInternalServiceTestNotificationRequest
     */
    'recipient_id'?: string;
    /**
     * 标题
     * @type {string}
     * @memberof PiemdmInternalServiceTestNotificationRequest
     */
    'title'?: string;
    /**
     * 变量
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalServiceTestNotificationRequest
     */
    'variables'?: { [key: string]: object; };
}

