/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelCron
 */
export interface PiemdmInternalModelCron {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'appId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'appKey'?: string;
    /**
     * Cron编码
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelCron
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'description'?: string;
    /**
     * 实体编码
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'entityCode'?: string;
    /**
     * Cron表达式
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'expression'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelCron
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'method'?: string;
    /**
     * 任务名称
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'name'?: string;
    /**
     * 协议类型，Http, Rest, GraphQL, GRPC, Soap, Jwt
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'protocol'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'signType'?: string;
    /**
     * 状态:Normal 正常, Frozen 已冻结, Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'status'?: string;
    /**
     * 系统名称
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'system'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'updatedBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCron
     */
    'url'?: string;
}

