/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalPkgRequestCreateApprovalNodeRequest
 */
export interface PiemdmInternalPkgRequestCreateApprovalNodeRequest {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'ApprovalDefCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'ApproverConfig'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'ApproverType'?: PiemdmInternalPkgRequestCreateApprovalNodeRequestApproverTypeEnum;
    /**
     * ApprovalMode    string `json:\"ApprovalMode\" binding:\"oneof=OR AND SEQUENTIAL\" comment:\"审批模式\"`
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'ConditionConfig'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'NodeCode': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'NodeName': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'NodeType': PiemdmInternalPkgRequestCreateApprovalNodeRequestNodeTypeEnum;
    /**
     * // TimeoutHours    int    `json:\"TimeoutHours\" binding:\"min=0,max=720\" comment:\"超时时间(小时)\"`
     * @type {number}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'SortOrder'?: number;
    /**
     * // IsRequired       bool   `json:\"IsRequired\" comment:\"是否必须\"` // AllowReject      bool   `json:\"AllowReject\" comment:\"允许拒绝\"` // AllowTransfer    bool   `json:\"AllowTransfer\" comment:\"允许转交\"` // AutoApprove      bool   `json:\"AutoApprove\" comment:\"自动审批\"` // NotifyConfig     string `json:\"NotifyConfig\" binding:\"max=2000\" comment:\"通知配置\"` // FormConfig       string `json:\"FormConfig\" binding:\"max=5000\" comment:\"表单配置\"` // PermissionConfig string `json:\"PermissionConfig\" binding:\"max=2000\" comment:\"权限配置\"` // Remark           string `json:\"Remark\" binding:\"max=500\" comment:\"备注\"`
     * @type {string}
     * @memberof PiemdmInternalPkgRequestCreateApprovalNodeRequest
     */
    'status'?: PiemdmInternalPkgRequestCreateApprovalNodeRequestStatusEnum;
}

export const PiemdmInternalPkgRequestCreateApprovalNodeRequestApproverTypeEnum = {
    Users: 'USERS',
    Roles: 'ROLES',
    Departments: 'DEPARTMENTS',
    AutoReject: 'AUTO_REJECT',
    AutoApprove: 'AUTO_APPROVE',
    System: 'SYSTEM'
} as const;

export type PiemdmInternalPkgRequestCreateApprovalNodeRequestApproverTypeEnum = typeof PiemdmInternalPkgRequestCreateApprovalNodeRequestApproverTypeEnum[keyof typeof PiemdmInternalPkgRequestCreateApprovalNodeRequestApproverTypeEnum];
export const PiemdmInternalPkgRequestCreateApprovalNodeRequestNodeTypeEnum = {
    Start: 'START',
    Approval: 'APPROVAL',
    Condition: 'CONDITION',
    AutoReject: 'AUTO_REJECT',
    AutoApprove: 'AUTO_APPROVE',
    Cc: 'CC',
    End: 'END'
} as const;

export type PiemdmInternalPkgRequestCreateApprovalNodeRequestNodeTypeEnum = typeof PiemdmInternalPkgRequestCreateApprovalNodeRequestNodeTypeEnum[keyof typeof PiemdmInternalPkgRequestCreateApprovalNodeRequestNodeTypeEnum];
export const PiemdmInternalPkgRequestCreateApprovalNodeRequestStatusEnum = {
    Normal: 'Normal',
    Frozen: 'Frozen',
    Deleted: 'Deleted'
} as const;

export type PiemdmInternalPkgRequestCreateApprovalNodeRequestStatusEnum = typeof PiemdmInternalPkgRequestCreateApprovalNodeRequestStatusEnum[keyof typeof PiemdmInternalPkgRequestCreateApprovalNodeRequestStatusEnum];


