/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalPkgRequestTransferTaskRequest
 */
export interface PiemdmInternalPkgRequestTransferTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestTransferTaskRequest
     */
    'reason': string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalPkgRequestTransferTaskRequest
     */
    'taskId': number;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestTransferTaskRequest
     */
    'toUserId': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestTransferTaskRequest
     */
    'toUserName': string;
}

