/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelApproval
 */
export interface PiemdmInternalModelApproval {
    /**
     * 审批定义编码
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'approvalDefCode': string;
    /**
     * 审批实例唯一编码
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'code'?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'createdAt'?: string;
    /**
     * 审计字段
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'createdBy'?: string;
    /**
     * 当前任务ID
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'currentTaskID'?: string;
    /**
     * 当前任务名称
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'currentTaskName'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelApproval
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 申请说明
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'description'?: string;
    /**
     * 关联实体编码
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'entityCode'?: string;
    /**
     * 表单数据
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'formData'?: string;
    /**
     * 表单结构JSON
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'formSchema'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelApproval
     */
    'id'?: number;
    /**
     * 审批信息
     * @type {number}
     * @memberof PiemdmInternalModelApproval
     */
    'priority'?: number;
    /**
     * 流程信息
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'serialNumber'?: string;
    /**
     * 状态信息，审批实例状态 可选值有： - Pending：审批中 - Approved：通过 - Rejected：拒绝 - Canceled：撤回 - Deleted：删除
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'status'?: string;
    /**
     * 审批标题
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'title': string;
    /**
     * 更新时间
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'updatedBy'?: string;
    /**
     * 紧急程度：Low/Normal/High/Urgent
     * @type {string}
     * @memberof PiemdmInternalModelApproval
     */
    'urgency'?: string;
}

