/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelWebhook
 */
export interface PiemdmInternalModelWebhook {
    /**
     * 请求方式：POST，GET 数据类型：plain，application/json，application/xxx-form-urlencoded，application/xml Data：string Headers；[]Key，Value Response示例 Basic Auth 用户名 Basic Auth 密码
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'contentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelWebhook
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'description'?: string;
    /**
     * 监控什么事件
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'events': string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelWebhook
     */
    'id'?: number;
    /**
     * AppSecret
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'secret': string;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'status'?: string;
    /**
     * 主数据Code
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'tableCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'updatedBy'?: string;
    /**
     * 调用Url
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'url': string;
    /**
     * 用户名
     * @type {string}
     * @memberof PiemdmInternalModelWebhook
     */
    'username'?: string;
}

