/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelWebhookDelivery
 */
export interface PiemdmInternalModelWebhookDelivery {
    /**
     * 完成时间
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'completedAt'?: string;
    /**
     * 投递时间
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'deliveredAt'?: string;
    /**
     * 调用编号
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'deliveryCode': string;
    /**
     * 实体编码
     * @type {number}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'entityID': number;
    /**
     * Event name: Release 发布(所有变更都会发布)
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'event'?: string;
    /**
     * WebHook编号
     * @type {number}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'hookID': number;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'id'?: number;
    /**
     * 请求头
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'requestHeaders'?: string;
    /**
     * 请求参数
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'requestPayload'?: string;
    /**
     * 回应信息
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'responseBody'?: string;
    /**
     * 回应头
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'responseHeaders'?: string;
    /**
     * 回应消息
     * @type {string}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'responseMessage'?: string;
    /**
     * 回应状态
     * @type {number}
     * @memberof PiemdmInternalModelWebhookDelivery
     */
    'responseStatus'?: number;
}

