/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelApprovalTask
 */
export interface PiemdmInternalModelApprovalTask {
    /**
     * 审批实例编码
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'approvalCode': string;
    /**
     * 审批人配置JSON
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'approverConfig'?: string;
    /**
     * 审批配置 审批方式 可选值有： AND：会签 OR：或签 AUTO_PASS：自动通过 AUTO_REJECT：自动拒绝 SEQUENTIAL：按顺序
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'approverType'?: string;
    /**
     * 审批人信息
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'assigneeID'?: string;
    /**
     * 审批人姓名
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'assigneeName'?: string;
    /**
     * 附件列表JSON
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'attachments'?: string;
    /**
     * 审批意见
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'createdAt'?: string;
    /**
     * 审计字段
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'id'?: number;
    /**
     * 节点编码
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'nodeCode'?: string;
    /**
     * 节点名称
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'nodeName'?: string;
    /**
     * node_type,approver_type,approver_config 三个字段暂时没有用 节点类型：START/APPROVAL/CONDITION/CC/END/PARALLEL/MERGE
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'nodeType'?: string;
    /**
     * 催办次数
     * @type {number}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'remindCount'?: number;
    /**
     * 任务状态 审批任务状态 可选值有： - PENDING：审批中 - APPROVED：通过 - REJECTED：拒绝 - TRANSFERRED：已转交 - DONE：完成
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'status'?: string;
    /**
     * 任务唯一编码
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'taskCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'updatedBy'?: string;
    /**
     * 审批信息 Priority     int    `gorm:\"default:0\"` // 优先级 紧急程度：Low/Normal/High/Urgent
     * @type {string}
     * @memberof PiemdmInternalModelApprovalTask
     */
    'urgency'?: string;
}

