/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldValidation
 */
export interface PiemdmInternalModelFieldValidation {
    /**
     * 格式: phone, email, url
     * @type {string}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'format'?: string;
    /**
     * 最大值
     * @type {number}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'max'?: number;
    /**
     * 自定义错误消息
     * @type {string}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'message'?: string;
    /**
     * 最小值
     * @type {number}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'min'?: number;
    /**
     * 自定义正则
     * @type {string}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'pattern'?: string;
    /**
     * 总位数 (仅 decimal 类型)
     * @type {number}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'precision'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'required'?: boolean;
    /**
     * 小数位数 (仅 decimal 类型)
     * @type {number}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'scale'?: number;
    /**
     * 预定义验证器: integer, email, phone, url
     * @type {string}
     * @memberof PiemdmInternalModelFieldValidation
     */
    'validator'?: string;
}

