/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelCronLog
 */
export interface PiemdmInternalModelCronLog {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'createdAt'?: string;
    /**
     * 结束时间
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'endTime'?: string;
    /**
     * 错误信息
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'errMsg'?: string;
    /**
     * 执行时间(秒)
     * @type {number}
     * @memberof PiemdmInternalModelCronLog
     */
    'execTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelCronLog
     */
    'id'?: number;
    /**
     * 任务名称
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'method': string;
    /**
     * 任务参数
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'param'?: string;
    /**
     * 开始时间
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'startTime'?: string;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelCronLog
     */
    'updatedAt'?: string;
}

