/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelRole } from './piemdm-internal-model-role';

/**
 * 
 * @export
 * @interface PiemdmInternalModelUser
 */
export interface PiemdmInternalModelUser {
    /**
     * 是否为管理员
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'admin': string;
    /**
     * 头像地址
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'avatar'?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelUser
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 简介
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'description'?: string;
    /**
     * 显示名称
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'displayName': string;
    /**
     * 邮箱
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'email': string;
    /**
     * 工号
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'employeeID': string;
    /**
     * 名称
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'firstName'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelUser
     */
    'id'?: number;
    /**
     * 语言
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'language'?: string;
    /**
     * 最后登录时间
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'lastLogin'?: string;
    /**
     * 姓氏
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'lastName'?: string;
    /**
     * 密码
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'password': string;
    /**
     * 权限列表(不持久化)
     * @type {Array<string>}
     * @memberof PiemdmInternalModelUser
     */
    'permissions'?: Array<string>;
    /**
     * 电话
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'phone'?: string;
    /**
     * 
     * @type {Array<PiemdmInternalModelRole>}
     * @memberof PiemdmInternalModelUser
     */
    'roles'?: Array<PiemdmInternalModelRole>;
    /**
     * 性别
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'sex'?: string;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'status'?: string;
    /**
     * 上级用户名
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'superiorUsername': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'updatedBy'?: string;
    /**
     * 用户名
     * @type {string}
     * @memberof PiemdmInternalModelUser
     */
    'username': string;
}

