/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalPkgRequestProcessApprovalRequest
 */
export interface PiemdmInternalPkgRequestProcessApprovalRequest {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestProcessApprovalRequest
     */
    'action': PiemdmInternalPkgRequestProcessApprovalRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestProcessApprovalRequest
     */
    'approvalCode': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestProcessApprovalRequest
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestProcessApprovalRequest
     */
    'nodeCode': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestProcessApprovalRequest
     */
    'reason'?: string;
}

export const PiemdmInternalPkgRequestProcessApprovalRequestActionEnum = {
    Approve: 'APPROVE',
    Reject: 'REJECT',
    Transfer: 'TRANSFER',
    Delegate: 'DELEGATE'
} as const;

export type PiemdmInternalPkgRequestProcessApprovalRequestActionEnum = typeof PiemdmInternalPkgRequestProcessApprovalRequestActionEnum[keyof typeof PiemdmInternalPkgRequestProcessApprovalRequestActionEnum];


