/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldAttachment } from './piemdm-internal-model-field-attachment';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldBehavior } from './piemdm-internal-model-field-behavior';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldDataSource } from './piemdm-internal-model-field-data-source';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldDateTime } from './piemdm-internal-model-field-date-time';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldRelation } from './piemdm-internal-model-field-relation';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldRichText } from './piemdm-internal-model-field-rich-text';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldSort } from './piemdm-internal-model-field-sort';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldUI } from './piemdm-internal-model-field-ui';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldValidation } from './piemdm-internal-model-field-validation';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelSequencePattern } from './piemdm-internal-model-sequence-pattern';

/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldOptions
 */
export interface PiemdmInternalModelFieldOptions {
    /**
     * 
     * @type {PiemdmInternalModelFieldAttachment}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'attachment'?: PiemdmInternalModelFieldAttachment;
    /**
     * 
     * @type {PiemdmInternalModelFieldBehavior}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'behavior'?: PiemdmInternalModelFieldBehavior;
    /**
     * 
     * @type {PiemdmInternalModelFieldDataSource}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'datasource'?: PiemdmInternalModelFieldDataSource;
    /**
     * 
     * @type {PiemdmInternalModelFieldDateTime}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'datetime'?: PiemdmInternalModelFieldDateTime;
    /**
     * 自动编码
     * @type {Array<PiemdmInternalModelSequencePattern>}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'patterns'?: Array<PiemdmInternalModelSequencePattern>;
    /**
     * 
     * @type {PiemdmInternalModelFieldRelation}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'relation'?: PiemdmInternalModelFieldRelation;
    /**
     * 
     * @type {PiemdmInternalModelFieldRichText}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'richtext'?: PiemdmInternalModelFieldRichText;
    /**
     * 
     * @type {PiemdmInternalModelFieldSort}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'sort'?: PiemdmInternalModelFieldSort;
    /**
     * 字符串去空格
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'trim'?: boolean;
    /**
     * 
     * @type {PiemdmInternalModelFieldUI}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'ui'?: PiemdmInternalModelFieldUI;
    /**
     * 
     * @type {PiemdmInternalModelFieldValidation}
     * @memberof PiemdmInternalModelFieldOptions
     */
    'validation'?: PiemdmInternalModelFieldValidation;
}

