/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM 主数据管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelTableExtension
 */
export interface PiemdmInternalModelTableExtension {
    /**
     * 基础表字段
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'baseField': string;
    /**
     * 基础表
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'baseTable': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'createdAt'?: string;
    /**
     * 这些都是服务端参数，不用校验。
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelTableExtension
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 扩展表中的关联字段
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'extField': string;
    /**
     * 扩展表的主键
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'extPrimary': string;
    /**
     * 扩展表
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'extTable': string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelTableExtension
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'name': string;
    /**
     * 扩展表在视图中的顺序
     * @type {number}
     * @memberof PiemdmInternalModelTableExtension
     */
    'sort'?: number;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelTableExtension
     */
    'updatedBy'?: string;
}

