/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldBehavior
 */
export interface PiemdmInternalModelFieldBehavior {
    /**
     * 
     * @type {object}
     * @memberof PiemdmInternalModelFieldBehavior
     */
    'defaultValue'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldBehavior
     */
    'readOnly'?: boolean;
    /**
     * 是否显示 (对应 is_show)
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldBehavior
     */
    'show'?: boolean;
    /**
     * 表达式
     * @type {string}
     * @memberof PiemdmInternalModelFieldBehavior
     */
    'visibleOn'?: string;
}

