/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelOptionItem } from './piemdm-internal-model-option-item';

/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldDataSource
 */
export interface PiemdmInternalModelFieldDataSource {
    /**
     * API
     * @type {string}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'api'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'fillBack'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'filter'?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'foreignKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'labelField'?: string;
    /**
     * Static
     * @type {Array<PiemdmInternalModelOptionItem>}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'options'?: Array<PiemdmInternalModelOptionItem>;
    /**
     * Relation
     * @type {string}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'targetTable'?: string;
    /**
     * static, api, relation
     * @type {string}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelFieldDataSource
     */
    'valueField'?: string;
}

