/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelTable
 */
export interface PiemdmInternalModelTable {
    /**
     * 展示模式：List 列表, Tree 树形
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'DisplayMode'?: PiemdmInternalModelTableDisplayModeEnum;
    /**
     * 父表关联字段
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'ParentField'?: string;
    /**
     * 父表Code（仅当TableType=Item时有效，不带t_前缀）
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'ParentTable'?: string;
    /**
     * 本表关联字段
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'SelfField'?: string;
    /**
     * 表类型：Entity 主表实体, Item 行项目
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'TableType'?: PiemdmInternalModelTableTableTypeEnum;
    /**
     * 表名,英文
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'createdAt'?: string;
    /**
     * 这些都是服务端参数，不用校验。
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelTable
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelTable
     */
    'id'?: number;
    /**
     * 名称，可以中文
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelTable
     */
    'sort'?: number;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelTable
     */
    'updatedBy'?: string;
}

export const PiemdmInternalModelTableDisplayModeEnum = {
    List: 'List',
    Tree: 'Tree'
} as const;

export type PiemdmInternalModelTableDisplayModeEnum = typeof PiemdmInternalModelTableDisplayModeEnum[keyof typeof PiemdmInternalModelTableDisplayModeEnum];
export const PiemdmInternalModelTableTableTypeEnum = {
    Entity: 'Entity',
    Item: 'Item'
} as const;

export type PiemdmInternalModelTableTableTypeEnum = typeof PiemdmInternalModelTableTableTypeEnum[keyof typeof PiemdmInternalModelTableTableTypeEnum];


