/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';
// May contain unused imports in some cases
// @ts-ignore
import { PiemdmInternalModelFieldOptions } from './piemdm-internal-model-field-options';

/**
 * 
 * @export
 * @interface PiemdmInternalModelTableField
 */
export interface PiemdmInternalModelTableField {
    /**
     * 编码
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'createdAt'?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelTableField
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 属性描述
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'description'?: string;
    /**
     * FieldType 目前会保存字段格式，在后端进行字段默认配置，字段校验等 后端的 FieldPreset 预设系统设计得非常完善，每个 FieldType 已经包含：   DataType (数据库类型)   Length (字段长度)   UI.Widget (UI 组件)   Validation (验证规则) 结论：不需要移除 FieldType，它是一个很好的设计！
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'fieldType'?: string;
    /**
     * 组名
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'groupName'?: string;
    /**
     * ===== field attr
     * @type {number}
     * @memberof PiemdmInternalModelTableField
     */
    'id'?: number;
    /**
     * 索引名称，扩展视图使用，不对外显示
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'indexName'?: string;
    /**
     * 索引名称，扩展视图使用，不对外显示
     * @type {number}
     * @memberof PiemdmInternalModelTableField
     */
    'indexPriority'?: number;
    /**
     * ===== show style
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'isFilter'?: string;
    /**
     * 是否创建索引，Yes,No
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'isIndex'?: string;
    /**
     * 是否展示字段  Yes：是  No-否
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'isShow'?: string;
    /**
     * 唯一标识，Yes,No
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'isUnique'?: string;
    /**
     * 属性长度
     * @type {number}
     * @memberof PiemdmInternalModelTableField
     */
    'length': number;
    /**
     * 属性名称
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'name': string;
    /**
     * 
     * @type {PiemdmInternalModelFieldOptions}
     * @memberof PiemdmInternalModelTableField
     */
    'options'?: PiemdmInternalModelFieldOptions;
    /**
     * 是否必填 Yes：必填 No:不必填
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'required'?: string;
    /**
     * 显示顺序
     * @type {number}
     * @memberof PiemdmInternalModelTableField
     */
    'sort'?: number;
    /**
     * ========== 状态 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'status'?: string;
    /**
     * 所属模型
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'tableCode': string;
    /**
     * 数据库字段类型(DB层): Text, Integer, Date, Decimal 等
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'updatedAt'?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof PiemdmInternalModelTableField
     */
    'updatedBy'?: string;
}

