/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldSort
 */
export interface PiemdmInternalModelFieldSort {
    /**
     * 排序作用域字段（如按 status 分组排序）
     * @type {string}
     * @memberof PiemdmInternalModelFieldSort
     */
    'scopeKey'?: string;
}

