/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldUI
 */
export interface PiemdmInternalModelFieldUI {
    /**
     * 占位符 (可选)
     * @type {string}
     * @memberof PiemdmInternalModelFieldUI
     */
    'placeholder'?: string;
    /**
     * 标题 (可选)
     * @type {string}
     * @memberof PiemdmInternalModelFieldUI
     */
    'title'?: string;
    /**
     * 组件类型 (必填)
     * @type {string}
     * @memberof PiemdmInternalModelFieldUI
     */
    'widget'?: string;
    /**
     * 组件参数 (可选)
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalModelFieldUI
     */
    'widgetProps'?: { [key: string]: object; };
}

