/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelSequencePattern
 */
export interface PiemdmInternalModelSequencePattern {
    /**
     * 配置选项
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalModelSequencePattern
     */
    'options'?: { [key: string]: object; };
    /**
     * string, integer, date
     * @type {string}
     * @memberof PiemdmInternalModelSequencePattern
     */
    'type'?: string;
}

