/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalPkgRequestStartApprovalRequest
 */
export interface PiemdmInternalPkgRequestStartApprovalRequest {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'approvalDefCode': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'entityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'expectedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'formData'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'priority'?: number;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'remark'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestStartApprovalRequest
     */
    'urgency'?: PiemdmInternalPkgRequestStartApprovalRequestUrgencyEnum;
}

export const PiemdmInternalPkgRequestStartApprovalRequestUrgencyEnum = {
    Low: 'LOW',
    Normal: 'NORMAL',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;

export type PiemdmInternalPkgRequestStartApprovalRequestUrgencyEnum = typeof PiemdmInternalPkgRequestStartApprovalRequestUrgencyEnum[keyof typeof PiemdmInternalPkgRequestStartApprovalRequestUrgencyEnum];


