/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldDateTime
 */
export interface PiemdmInternalModelFieldDateTime {
    /**
     * 日期格式
     * @type {string}
     * @memberof PiemdmInternalModelFieldDateTime
     */
    'dateFormat'?: string;
    /**
     * 创建时默认当前时间
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldDateTime
     */
    'defaultToCurrentTime'?: boolean;
    /**
     * 更新时自动更新为当前时间
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldDateTime
     */
    'onUpdateToCurrentTime'?: boolean;
    /**
     * 是否显示时间选择器
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldDateTime
     */
    'showTime'?: boolean;
    /**
     * 时间格式
     * @type {string}
     * @memberof PiemdmInternalModelFieldDateTime
     */
    'timeFormat'?: string;
    /**
     * 是否支持时区
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldDateTime
     */
    'timezone'?: boolean;
}

