/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelOptionItem
 */
export interface PiemdmInternalModelOptionItem {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelOptionItem
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelOptionItem
     */
    'label'?: string;
    /**
     * 
     * @type {object}
     * @memberof PiemdmInternalModelOptionItem
     */
    'value'?: object;
}

