/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldRelation
 */
export interface PiemdmInternalModelFieldRelation {
    /**
     * 过滤条件
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalModelFieldRelation
     */
    'filter'?: { [key: string]: object; };
    /**
     * 外键（可自动生成）
     * @type {string}
     * @memberof PiemdmInternalModelFieldRelation
     */
    'foreignKey'?: string;
    /**
     * 显示字段（默认 name）
     * @type {string}
     * @memberof PiemdmInternalModelFieldRelation
     */
    'labelField'?: string;
    /**
     * 是否多选
     * @type {boolean}
     * @memberof PiemdmInternalModelFieldRelation
     */
    'multiple'?: boolean;
    /**
     * 关联表
     * @type {string}
     * @memberof PiemdmInternalModelFieldRelation
     */
    'target'?: string;
    /**
     * 存储字段 = 关联键（默认 code）
     * @type {string}
     * @memberof PiemdmInternalModelFieldRelation
     */
    'valueField'?: string;
}

