/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface PiemdmInternalModelApplication
 */
export interface PiemdmInternalModelApplication {
    /**
     * AppId
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'appId'?: string;
    /**
     * AppSecret
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'appSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'createdBy'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof PiemdmInternalModelApplication
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 简介
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalModelApplication
     */
    'id'?: number;
    /**
     * 系统来源IP
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'ip'?: string;
    /**
     * 系统名称
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'name'?: string;
    /**
     * 状态：Normal 正常 Frozen 已冻结 Deleted 已删除
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalModelApplication
     */
    'updatedBy'?: string;
}

