/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalModelFieldRichText
 */
export interface PiemdmInternalModelFieldRichText {
    /**
     * 附件存储集合名称
     * @type {string}
     * @memberof PiemdmInternalModelFieldRichText
     */
    'fileCollection'?: string;
    /**
     * short, long
     * @type {string}
     * @memberof PiemdmInternalModelFieldRichText
     */
    'length'?: string;
    /**
     * 工具栏配置
     * @type {Array<string>}
     * @memberof PiemdmInternalModelFieldRichText
     */
    'toolbar'?: Array<string>;
}

