/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalServiceTemplateNotificationRequest
 */
export interface PiemdmInternalServiceTemplateNotificationRequest {
    /**
     * 审批实例ID（可选）
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'approval_id'?: string;
    /**
     * 过期时间
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'expire_time'?: string;
    /**
     * 通知类型
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'notification_type'?: string;
    /**
     * 优先级
     * @type {number}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'priority'?: number;
    /**
     * 接收人ID
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'recipient_id'?: string;
    /**
     * 接收人类型
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'recipient_type'?: string;
    /**
     * 任务ID（可选）
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'task_id'?: string;
    /**
     * 模板编码
     * @type {string}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'template_code'?: string;
    /**
     * 模板变量
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalServiceTemplateNotificationRequest
     */
    'variables'?: { [key: string]: object; };
}

