/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalServiceCreateNotificationTemplateRequest
 */
export interface PiemdmInternalServiceCreateNotificationTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'ContentTemplate': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'CreatedBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'NotificationType': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'Status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'TemplateCode': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'TemplateName': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'TemplateType': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'TitleTemplate': string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof PiemdmInternalServiceCreateNotificationTemplateRequest
     */
    'Variables'?: { [key: string]: object; };
}

