/* tslint:disable */
/* eslint-disable */
/**
 * PieMDM API
 * PieMDM Master Data Management System API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@piemdm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PiemdmInternalPkgRequestUpdateApprovalNodeRequest
 */
export interface PiemdmInternalPkgRequestUpdateApprovalNodeRequest {
    /**
     * 
     * @type {boolean}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'allowReject'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'allowTransfer'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'approvalMode'?: PiemdmInternalPkgRequestUpdateApprovalNodeRequestApprovalModeEnum;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'approverConfig'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'approverType'?: PiemdmInternalPkgRequestUpdateApprovalNodeRequestApproverTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'autoApprove'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'conditionConfig'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'formConfig'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'isRequired'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'nodeName': string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'nodeType': PiemdmInternalPkgRequestUpdateApprovalNodeRequestNodeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'notifyConfig'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'permissionConfig'?: string;
    /**
     * 
     * @type {string}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'remark'?: string;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'sortOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof PiemdmInternalPkgRequestUpdateApprovalNodeRequest
     */
    'timeoutHours'?: number;
}

export const PiemdmInternalPkgRequestUpdateApprovalNodeRequestApprovalModeEnum = {
    Or: 'OR',
    And: 'AND',
    Sequential: 'SEQUENTIAL'
} as const;

export type PiemdmInternalPkgRequestUpdateApprovalNodeRequestApprovalModeEnum = typeof PiemdmInternalPkgRequestUpdateApprovalNodeRequestApprovalModeEnum[keyof typeof PiemdmInternalPkgRequestUpdateApprovalNodeRequestApprovalModeEnum];
export const PiemdmInternalPkgRequestUpdateApprovalNodeRequestApproverTypeEnum = {
    User: 'USER',
    Role: 'ROLE',
    Dept: 'DEPT',
    Expression: 'EXPRESSION'
} as const;

export type PiemdmInternalPkgRequestUpdateApprovalNodeRequestApproverTypeEnum = typeof PiemdmInternalPkgRequestUpdateApprovalNodeRequestApproverTypeEnum[keyof typeof PiemdmInternalPkgRequestUpdateApprovalNodeRequestApproverTypeEnum];
export const PiemdmInternalPkgRequestUpdateApprovalNodeRequestNodeTypeEnum = {
    Start: 'START',
    Approval: 'APPROVAL',
    Condition: 'CONDITION',
    Parallel: 'PARALLEL',
    Merge: 'MERGE',
    Cc: 'CC',
    End: 'END'
} as const;

export type PiemdmInternalPkgRequestUpdateApprovalNodeRequestNodeTypeEnum = typeof PiemdmInternalPkgRequestUpdateApprovalNodeRequestNodeTypeEnum[keyof typeof PiemdmInternalPkgRequestUpdateApprovalNodeRequestNodeTypeEnum];


